const AARTIS_DATA = [
  {
    "category": "गणेश",
    "title": "श्री गणेश आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-ganesh-ji-aarti-in-hindi-english",
    "opening": "जय गणेश जय गणेश,",
    "id": 1,
    "lyrics": "जय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\nएक दंत दयावंत,\nचार भुजा धारी ।\nमाथे सिंदूर सोहे,\nमूसे की सवारी ॥\nजय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\nपान चढ़े फल चढ़े,\nऔर चढ़े मेवा ।\nलड्डुअन का भोग लगे,\nसंत करें सेवा ॥\nजय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\nअंधन को आंख देत,\nकोढ़िन को काया ।\nबांझन को पुत्र देत,\nनिर्धन को माया ॥\nजय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\n'सूर' श्याम शरण आए,\nसफल कीजे सेवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\nजय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥\n\nदीनन की लाज रखो,\nशंभु सुतकारी ।\nकामना को पूर्ण करो,\nजाऊं बलिहारी ॥\nजय गणेश जय गणेश,\nजय गणेश देवा ।\nमाता जाकी पार्वती,\nपिता महादेवा ॥",
    "romanTitle": "Shri Ganesh Aarti",
    "romanLyrics": "Jay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva ..\nek dant dayavant,\nchar bhuja dhari .\nmathe sindur sohe,\nmuse ki savari ..\nJay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva ..\npan charhe phal charhe,\naur charhe meva .\nladduan ka bhog lage,\nsamt karen seva ..\nJay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva ..\namdhan ko ankh det,\nkorhin ko kaya .\nbamjhan ko putra det,\nnirdhan ko maya ..\nJay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva ..\n'sur' shyam sharan ae,\nsaphal kije seva .\nmata jaki parvati,\npita mahadeva ..\nJay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva ..\n\ndinan ki laj rakho,\nshambhu sutkari .\nkamna ko purn karo,\njaum balihari ..\nJay Ganesh Jay Ganesh,\nJay Ganesh deva .\nmata jaki parvati,\npita mahadeva .."
  },
  {
    "category": "विष्णु",
    "title": "ॐ जय जगदीश हरे",
    "url": "https://www.bhaktibharat.com/aarti/om-jai-jagdish-hare",
    "opening": "ॐ जय जगदीश हरे,",
    "id": 2,
    "lyrics": "ॐ जय जगदीश हरे,\nस्वामी जय जगदीश हरे ।\nभक्त जनों के संकट,\nदास जनों के संकट,\nक्षण में दूर करे ॥\n॥ ॐ जय जगदीश हरे..॥\nजो ध्यावे फल पावे,\nदुःख बिनसे मन का,\nस्वामी दुःख बिनसे मन का ।\nसुख सम्पति घर आवे,\nसुख सम्पति घर आवे,\nकष्ट मिटे तन का ॥\n॥ ॐ जय जगदीश हरे..॥\nमात पिता तुम मेरे,\nशरण गहूं किसकी,\nस्वामी शरण गहूं मैं किसकी ।\nतुम बिन और न दूजा,\nतुम बिन और न दूजा,\nआस करूं मैं जिसकी ॥\n॥ ॐ जय जगदीश हरे..॥\nतुम पूरण परमात्मा,\nतुम अन्तर्यामी,\nस्वामी तुम अन्तर्यामी ।\nपारब्रह्म परमेश्वर,\nपारब्रह्म परमेश्वर,\nतुम सब के स्वामी ॥\n॥ ॐ जय जगदीश हरे..॥\nतुम करुणा के सागर,\nतुम पालनकर्ता,\nस्वामी तुम पालनकर्ता ।\nमैं मूरख फलकामी,\nमैं सेवक तुम स्वामी,\nकृपा करो भर्ता॥\n॥ ॐ जय जगदीश हरे..॥\nतुम हो एक अगोचर,\nसबके प्राणपति,\nस्वामी सबके प्राणपति ।\nकिस विधि मिलूं दयामय,\nकिस विधि मिलूं दयामय,\nतुमको मैं कुमति ॥\n॥ ॐ जय जगदीश हरे..॥\nदीन-बन्धु दुःख-हर्ता,\nठाकुर तुम मेरे,\nस्वामी रक्षक तुम मेरे ।\nअपने हाथ उठाओ,\nअपने शरण लगाओ,\nद्वार पड़ा तेरे ॥\n॥ ॐ जय जगदीश हरे..॥\nविषय-विकार मिटाओ,\nपाप हरो देवा,\nस्वमी पाप(कष्ट) हरो देवा ।\nश्रद्धा भक्ति बढ़ाओ,\nश्रद्धा भक्ति बढ़ाओ,\nसन्तन की सेवा ॥\nॐ जय जगदीश हरे,\nस्वामी जय जगदीश हरे ।\nभक्त जनों के संकट,\nदास जनों के संकट,\nक्षण में दूर करे ॥",
    "romanTitle": "Om Jay Jagdish hare",
    "romanLyrics": "Om Jay Jagdish hare,\nswami Jay Jagdish hare .\nbhakt janOm ke sankat,\ndas janOm ke sankat,\nkshan mem dur kare ..\n.. Om Jay Jagdish hare....\njo dhyave phal pave,\nduhkh binse man ka,\nswami duhkh binse man ka .\nsukh sampati ghar ave,\nsukh sampati ghar ave,\nkasht mite tan ka ..\n.. Om Jay Jagdish hare....\nmat pita tum mere,\nsharan gahum kiski,\nswami sharan gahum maim kiski .\ntum bin aur na duja,\ntum bin aur na duja,\nas karum maim jiski ..\n.. Om Jay Jagdish hare....\ntum puran paramatma,\ntum antaryami,\nswami tum antaryami .\nparabrahma parameshvar,\nparabrahma parameshvar,\ntum sab ke swami ..\n.. Om Jay Jagdish hare....\ntum karuna ke sagar,\ntum palanakarta,\nswami tum palanakarta .\nmaim murakh phalkami,\nmaim sevak tum swami,\nkripa karo bharta..\n.. Om Jay Jagdish hare....\ntum ho ek agochar,\nsabke pranpati,\nswami sabke pranpati .\nkis vidhi milum dayamay,\nkis vidhi milum dayamay,\ntumko maim kumti ..\n.. Om Jay Jagdish hare....\ndin-bandhu duhkh-harta,\nthakur tum mere,\nswami rakshak tum mere .\napne hath uthao,\napne sharan lagao,\ndvar para tere ..\n.. Om Jay Jagdish hare....\nvishay-vikar mitao,\npap haro deva,\nswami pap(kasht) haro deva .\nshraddha bhakti barhao,\nshraddha bhakti barhao,\nsantan ki seva ..\nOm Jay Jagdish hare,\nswami Jay Jagdish hare .\nbhakt janOm ke sankat,\ndas janOm ke sankat,\nkshan mem dur kare .."
  },
  {
    "category": "शिव",
    "title": "ॐ जय शिव ओंकारा",
    "url": "https://www.bhaktibharat.com/aarti/shri-shiv-shankar-bholenath",
    "opening": "ॐ जय शिव ओंकारा,",
    "id": 3,
    "lyrics": "ॐ जय शिव ओंकारा,\nस्वामी जय शिव ओंकारा।\nब्रह्मा, विष्णु, सदाशिव,\nअर्द्धांगी धारा ॥\nॐ जय शिव ओंकारा...॥\nएकानन चतुरानन\nपंचानन राजे ।\nहंसासन गरूड़ासन\nवृषवाहन साजे ॥\nॐ जय शिव ओंकारा...॥\nदो भुज चार चतुर्भुज\nदसभुज अति सोहे ।\nत्रिगुण रूप निरखते\nत्रिभुवन जन मोहे ॥\nॐ जय शिव ओंकारा...॥\nअक्षमाला वनमाला,\nमुण्डमाला धारी ।\nचंदन मृगमद सोहै,\nभाले शशिधारी ॥\nॐ जय शिव ओंकारा...॥\nश्वेताम्बर पीताम्बर\nबाघम्बर अंगे ।\nसनकादिक गरुणादिक\nभूतादिक संगे ॥\nॐ जय शिव ओंकारा...॥\nकर के मध्य कमंडल\nचक्र त्रिशूलधारी ।\nसुखकारी दुखहारी\nजगपालन कारी ॥\nॐ जय शिव ओंकारा...॥\nब्रह्मा विष्णु सदाशिव\nजानत अविवेका ।\nप्रणवाक्षर में शोभित\nये तीनों एका ॥\nॐ जय शिव ओंकारा...॥\nत्रिगुणस्वामी जी की आरति\nजो कोइ नर गावे ।\nकहत शिवानंद स्वामी\nसुख संपति पावे ॥\nॐ जय शिव ओंकारा...॥\n\nलक्ष्मी व सावित्री\nपार्वती संगा ।\nपार्वती अर्द्धांगी,\nशिवलहरी गंगा ॥\nॐ जय शिव ओंकारा...॥\nपर्वत सोहैं पार्वती,\nशंकर कैलासा ।\nभांग धतूर का भोजन,\nभस्मी में वासा ॥\nॐ जय शिव ओंकारा...॥\nजटा में गंग बहत है,\nगल मुण्डन माला ।\nशेष नाग लिपटावत,\nओढ़त मृगछाला ॥\nजय शिव ओंकारा...॥\nकाशी में विराजे विश्वनाथ,\nनंदी ब्रह्मचारी ।\nनित उठ दर्शन पावत,\nमहिमा अति भारी ॥\nॐ जय शिव ओंकारा...॥\nॐ जय शिव ओंकारा,\nस्वामी जय शिव ओंकारा।\nब्रह्मा, विष्णु, सदाशिव,\nअर्द्धांगी धारा ॥",
    "romanTitle": "Om jay shiv omkara",
    "romanLyrics": "Om jay shiv omkara,\nswami jay shiv omkara.\nbrahma, vishnu, sadashiv,\narddhamgi dhara ..\nOm jay shiv omkara.....\nekanan chaturanan\npamchanan raje .\nhamsasan garurasan\nvrishavahan saje ..\nOm jay shiv omkara.....\ndo bhuj char chaturbhuj\ndasbhuj ati sohe .\ntrigun rup nirkhate\ntribhuvan jan mohe ..\nOm jay shiv omkara.....\nakshamala vanmala,\nmundamala dhari .\nchamdan mrigmad sohai,\nbhale shashidhari ..\nOm jay shiv omkara.....\nshvetambar pitambar\nbaghambar amge .\nsanakadik garunadik\nbhutadik samge ..\nOm jay shiv omkara.....\nkar ke madhya kamandal\nchakra trishuldhari .\nsukhkari dukhhari\njagapalan kari ..\nOm jay shiv omkara.....\nbrahma vishnu sadashiv\njanat aviveka .\npranavakshar mem shobhit\nye tinOm eka ..\nOm jay shiv omkara.....\ntrigunaswami ji ki aarti\njo koi nar gave .\nkahat shivanamd swami\nsukh sampti pave ..\nOm jay shiv omkara.....\n\nlakshmi va savitri\nparvati samga .\nparvati arddhamgi,\nshivalhari ganga ..\nOm jay shiv omkara.....\nparvat sohaim parvati,\nshankar kailasa .\nbhamg dhatur ka bhojan,\nbhasmi mem vasa ..\nOm jay shiv omkara.....\njata mem gang bahat hai,\ngal mundan mala .\nshesh nag lipatavat,\norhat mrigchhala ..\njay shiv omkara.....\nkashi mem viraje vishvanath,\nnamdi brahmachari .\nnit uth darshan pavat,\nmahima ati bhari ..\nOm jay shiv omkara.....\nOm jay shiv omkara,\nswami jay shiv omkara.\nbrahma, vishnu, sadashiv,\narddhamgi dhara .."
  },
  {
    "category": "हनुमान",
    "title": "आरती कीजै हनुमान लला की",
    "url": "https://www.bhaktibharat.com/aarti/shri-hanuman-ji-ki-aarti",
    "opening": "आरती कीजै हनुमान लला की ।",
    "id": 4,
    "lyrics": "आरती कीजै हनुमान लला की ।\nदुष्ट दलन रघुनाथ कला की ॥\nजाके बल से गिरवर काँपे ।\nरोग-दोष जाके निकट न झाँके ॥\nअंजनि पुत्र महा बलदाई ।\nसंतन के प्रभु सदा सहाई ॥\nआरती कीजै हनुमान लला की ॥\nदे वीरा रघुनाथ पठाए ।\nलंका जारि सिया सुधि लाये ॥\nलंका सो कोट समुद्र सी खाई ।\nजात पवनसुत बार न लाई ॥\nआरती कीजै हनुमान लला की ॥\nलंका जारि असुर संहारे ।\nसियाराम जी के काज सँवारे ॥\nलक्ष्मण मुर्छित पड़े सकारे ।\nलाये संजिवन प्राण उबारे ॥\nआरती कीजै हनुमान लला की ॥\nपैठि पताल तोरि जमकारे ।\nअहिरावण की भुजा उखारे ॥\nबाईं भुजा असुर दल मारे ।\nदाहिने भुजा संतजन तारे ॥\nआरती कीजै हनुमान लला की ॥\nसुर-नर-मुनि जन आरती उतरें ।\nजय जय जय हनुमान उचारें ॥\nकंचन थार कपूर लौ छाई ।\nआरती करत अंजना माई ॥\nआरती कीजै हनुमान लला की ॥\nजो हनुमानजी की आरती गावे ।\nबसहिं बैकुंठ परम पद पावे ॥\nलंक विध्वंस किये रघुराई ।\nतुलसीदास स्वामी कीर्ति गाई ॥\nआरती कीजै हनुमान लला की ।\nदुष्ट दलन रघुनाथ कला की ॥",
    "romanTitle": "aarti kijai hanuman lala ki",
    "romanLyrics": "aarti kijai hanuman lala ki .\ndusht dalan raghunath kala ki ..\njake bal se girvar kampe .\nrog-dosh jake nikat na jhanke ..\namjni putra maha baladai .\nsamtan ke prabhu sada sahai ..\naarti kijai hanuman lala ki ..\nde vira raghunath pathae .\nlanka jari siya sudhi laye ..\nlanka so kot samudra si khai .\njat pavansut bar na lai ..\naarti kijai hanuman lala ki ..\nlanka jari asur samhare .\nsiyaram ji ke kaj samvare ..\nlakshman murchhit pare sakare .\nlaye samjivan pran ubare ..\naarti kijai hanuman lala ki ..\npaithi patal tori jankare .\nahiravan ki bhuja ukhare ..\nbaim bhuja asur dal mare .\ndahine bhuja samtjan tare ..\naarti kijai hanuman lala ki ..\nsur-nar-muni jan aarti utrem .\njay jay jay hanuman ucharem ..\nkamchan thar kapur lau chhai .\naarti karat amjna mai ..\naarti kijai hanuman lala ki ..\njo hanumanji ki aarti gave .\nbashim baikumth param pad pave ..\nlank vidhvams kiye raghurai .\ntulasidas swami kirti gai ..\naarti kijai hanuman lala ki .\ndusht dalan raghunath kala ki .."
  },
  {
    "category": "दुर्गा",
    "title": "जय अम्बे गौरी",
    "url": "https://www.bhaktibharat.com/aarti/jai-ambe-gauri-maiya-jai-shyama-gauri",
    "opening": "जय अम्बे गौरी,",
    "id": 5,
    "lyrics": "जय अम्बे गौरी,\nमैया जय श्यामा गौरी ।\nतुमको निशदिन ध्यावत,\nहरि ब्रह्मा शिवरी ॥\nॐ जय अम्बे गौरी..॥\nमांग सिंदूर विराजत,\nटीको मृगमद को ।\nउज्ज्वल से दोउ नैना,\nचंद्रवदन नीको ॥\nॐ जय अम्बे गौरी..॥\nकनक समान कलेवर,\nरक्ताम्बर राजै ।\nरक्तपुष्प गल माला,\nकंठन पर साजै ॥\nॐ जय अम्बे गौरी..॥\nकेहरि वाहन राजत,\nखड्ग खप्पर धारी ।\nसुर-नर-मुनिजन सेवत,\nतिनके दुखहारी ॥\nॐ जय अम्बे गौरी..॥\nकानन कुण्डल शोभित,\nनासाग्रे मोती ।\nकोटिक चंद्र दिवाकर,\nसम राजत ज्योती ॥\nॐ जय अम्बे गौरी..॥\nशुंभ-निशुंभ बिदारे,\nमहिषासुर घाती ।\nधूम्र विलोचन नैना,\nनिशदिन मदमाती ॥\nॐ जय अम्बे गौरी..॥\nचण्ड-मुण्ड संहारे,\nशोणित बीज हरे ।\nमधु-कैटभ दोउ मारे,\nसुर भयहीन करे ॥\nॐ जय अम्बे गौरी..॥\nब्रह्माणी, रूद्राणी,\nतुम कमला रानी ।\nआगम निगम बखानी,\nतुम शिव पटरानी ॥\nॐ जय अम्बे गौरी..॥\nचौंसठ योगिनी मंगल गावत,\nनृत्य करत भैरों ।\nबाजत ताल मृदंगा,\nअरू बाजत डमरू ॥\nॐ जय अम्बे गौरी..॥\nतुम ही जग की माता,\nतुम ही हो भरता,\nभक्तन की दुख हरता ।\nसुख संपति करता ॥\nॐ जय अम्बे गौरी..॥\nभुजा चार अति शोभित,\nवर मुद्रा धारी । [खड्ग खप्पर धारी]\nमनवांछित फल पावत,\nसेवत नर नारी ॥\nॐ जय अम्बे गौरी..॥\nकंचन थाल विराजत,\nअगर कपूर बाती ।\nश्रीमालकेतु में राजत,\nकोटि रतन ज्योती ॥\nॐ जय अम्बे गौरी..॥\nश्री अंबेजी की आरति,\nजो कोइ नर गावे ।\nकहत शिवानंद स्वामी,\nसुख-संपति पावे ॥\nॐ जय अम्बे गौरी..॥\nजय अम्बे गौरी,\nमैया जय श्यामा गौरी ।",
    "romanTitle": "jay ambe gauri",
    "romanLyrics": "jay ambe gauri,\nmaiya jay shyama gauri .\ntumko nishdin dhyavat,\nhari brahma shivri ..\nOm jay ambe gauri....\nmaag sindur virajat,\ntiko mrigmad ko .\nujjval se dou naina,\nchamdravdan niko ..\nOm jay ambe gauri....\nkanak saman kalevar,\nraktambar rajai .\nraktapushp gal mala,\nkamthan par sajai ..\nOm jay ambe gauri....\nkehri vahan rajat,\nkhadga khappar dhari .\nsur-nar-munijan sevat,\ntinke dukhhari ..\nOm jay ambe gauri....\nkanan kundal shobhit,\nnasagre moti .\nkotik chamdra divakar,\nsam rajat jyoti ..\nOm jay ambe gauri....\nshumbh-nishumbh bidare,\nmahishasur ghati .\ndhumra vilochan naina,\nnishdin madmati ..\nOm jay ambe gauri....\nchand-mund samhare,\nshonit bij hare .\nmadhu-kaitabh dou mare,\nsur bhayhin kare ..\nOm jay ambe gauri....\nbrahmani, rudrani,\ntum kamla rani .\nagam nigam bakhani,\ntum shiv patrani ..\nOm jay ambe gauri....\nchaumsath yogini maagal gavat,\nnritya karat bhairOm .\nbajat tal mridamga,\naru bajat damru ..\nOm jay ambe gauri....\ntum hi jag ki mata,\ntum hi ho bharta,\nbhaktan ki dukh harta .\nsukh sampti karta ..\nOm jay ambe gauri....\nbhuja char ati shobhit,\nvar mudra dhari . [khadga khappar dhari]\nmanavamchhit phal pavat,\nsevat nar nari ..\nOm jay ambe gauri....\nkamchan thal virajat,\nagar kapur bati .\nshrimalketu mem rajat,\nkoti ratan jyoti ..\nOm jay ambe gauri....\nshri ambeji ki aarti,\njo koi nar gave .\nkahat shivanamd swami,\nsukh-sampti pave ..\nOm jay ambe gauri....\njay ambe gauri,\nmaiya jay shyama gauri ."
  },
  {
    "category": "लक्ष्मी",
    "title": "ॐ जय लक्ष्मी माता",
    "url": "https://www.bhaktibharat.com/aarti/shri-laxmi-mata",
    "opening": "ॐ जय लक्ष्मी माता,",
    "id": 6,
    "lyrics": "ॐ जय लक्ष्मी माता,\nमैया जय लक्ष्मी माता ।\nतुमको निसदिन सेवत,\nहर विष्णु विधाता ॥\nउमा, रमा, ब्रम्हाणी,\nतुम ही जग माता ।\nसूर्य चद्रंमा ध्यावत,\nनारद ऋषि गाता ॥\nॐ जय लक्ष्मी माता...॥\nदुर्गा रुप निरंजनि,\nसुख-संपत्ति दाता ।\nजो कोई तुमको ध्याता,\nऋद्धि-सिद्धि धन पाता ॥\nॐ जय लक्ष्मी माता...॥\nतुम ही पाताल निवासनी,\nतुम ही शुभदाता ।\nकर्म-प्रभाव-प्रकाशनी,\nभव निधि की त्राता ॥\nॐ जय लक्ष्मी माता...॥\nजिस घर तुम रहती हो,\nताँहि में हैं सद्‍गुण आता ।\nसब सभंव हो जाता,\nमन नहीं घबराता ॥\nॐ जय लक्ष्मी माता...॥\nतुम बिन यज्ञ ना होता,\nवस्त्र न कोई पाता ।\nखान पान का वैभव,\nसब तुमसे आता ॥\nॐ जय लक्ष्मी माता...॥\nशुभ गुण मंदिर सुंदर,\nक्षीरोदधि जाता ।\nरत्न चतुर्दश तुम बिन,\nकोई नहीं पाता ॥\nॐ जय लक्ष्मी माता...॥\nमहालक्ष्मी जी की आरती,\nजो कोई नर गाता ।\nउँर आंनद समाता,\nपाप उतर जाता ॥\nॐ जय लक्ष्मी माता...॥\nॐ जय लक्ष्मी माता,\nमैया जय लक्ष्मी माता ।\nतुमको निसदिन सेवत,\nहर विष्णु विधाता ॥",
    "romanTitle": "Om jay lakshmi mata",
    "romanLyrics": "Om jay lakshmi mata,\nmaiya jay lakshmi mata .\ntumko nisdin sevat,\nhar vishnu vidhata ..\numa, rama, bramhani,\ntum hi jag mata .\nsurya chadramma dhyavat,\nnarad rishi gata ..\nOm jay lakshmi mata.....\ndurga rup niramjni,\nsukh-sampatti data .\njo koi tumko dhyata,\nriddhi-siddhi dhan pata ..\nOm jay lakshmi mata.....\ntum hi patal nivasni,\ntum hi shubhdata .\nkarm-prabhav-prakashni,\nbhav nidhi ki trata ..\nOm jay lakshmi mata.....\njis ghar tum rahti ho,\ntamhi mem haim sadgun ata .\nsab sabhamv ho jata,\nman nahim ghabrata ..\nOm jay lakshmi mata.....\ntum bin yajnya na hota,\nvastra na koi pata .\nkhan pan ka vaibhav,\nsab tumse ata ..\nOm jay lakshmi mata.....\nshubh gun mandir sumdar,\nkshiroddhi jata .\nratna chaturdash tum bin,\nkoi nahim pata ..\nOm jay lakshmi mata.....\nmahalakshmi ji ki aarti,\njo koi nar gata .\numr amnad samata,\npap utar jata ..\nOm jay lakshmi mata.....\nOm jay lakshmi mata,\nmaiya jay lakshmi mata .\ntumko nisdin sevat,\nhar vishnu vidhata .."
  },
  {
    "category": "कृष्ण",
    "title": "आरती कुंजबिहारी की",
    "url": "https://www.bhaktibharat.com/aarti/kunj-bihari-shri-girdhar-krishna-murari",
    "opening": "आरती कुंजबिहारी की,",
    "id": 7,
    "lyrics": "आरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nगले में बैजंती माला,\nबजावै मुरली मधुर बाला ।\nश्रवण में कुण्डल झलकाला,\nनंद के आनंद नंदलाला ।\nगगन सम अंग कांति काली,\nराधिका चमक रही आली ।\nलतन में ठाढ़े बनमाली\nभ्रमर सी अलक,\nकस्तूरी तिलक,\nचंद्र सी झलक,\nललित छवि श्यामा प्यारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nकनकमय मोर मुकुट बिलसै,\nदेवता दरसन को तरसैं ।\nगगन सों सुमन रासि बरसै ।\nबजे मुरचंग,\nमधुर मिरदंग,\nग्वालिन संग,\nअतुल रति गोप कुमारी की,\nश्री गिरिधर कृष्णमुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nजहां ते प्रकट भई गंगा,\nसकल मन हारिणि श्री गंगा ।\nस्मरन ते होत मोह भंगा\nबसी शिव सीस,\nजटा के बीच,\nहरै अघ कीच,\nचरन छवि श्रीबनवारी की,\nश्री गिरिधर कृष्णमुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nचमकती उज्ज्वल तट रेनू,\nबज रही वृंदावन बेनू ।\nचहुं दिसि गोपि ग्वाल धेनू\nहंसत मृदु मंद,\nचांदनी चंद,\nकटत भव फंद,\nटेर सुन दीन दुखारी की,\nश्री गिरिधर कृष्णमुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥\nआरती कुंजबिहारी की,\nश्री गिरिधर कृष्ण मुरारी की ॥",
    "romanTitle": "aarti kunjabihari ki",
    "romanLyrics": "aarti kunjabihari ki,\nshri giridhar krishna murari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\ngale mem baijamti mala,\nbajavai murli madhur bala .\nshravan mem kundal jhalkala,\nnamd ke anamd namdlala .\ngagan sam amg kamti kali,\nradhika chamak rahi ali .\nlatan mem tharhe banmali\nbhramar si alak,\nkasturi tilak,\nchamdra si jhalak,\nlalit chhavi shyama pyari ki,\nshri giridhar krishna murari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\nkanakmay mor mukut bilsai,\ndevta darsan ko tarsaim .\ngagan som suman rasi barsai .\nbaje murachamg,\nmadhur miradamg,\ngvalin samg,\natul rati gop kumari ki,\nshri giridhar krishnamurari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\njaham te prakat bhai ganga,\nsakal man harini shri ganga .\nsmaran te hot moh bhamga\nbasi shiv sis,\njata ke bich,\nharai agh kich,\ncharan chhavi shribanvari ki,\nshri giridhar krishnamurari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\nchankati ujjval tat renu,\nbaj rahi vrimdavan benu .\nchahum disi gopi gval dhenu\nhamsat mridu mand,\nchamdni chamd,\nkatat bhav phamd,\nter sun din dukhari ki,\nshri giridhar krishnamurari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki ..\naarti kunjabihari ki,\nshri giridhar krishna murari ki .."
  },
  {
    "category": "सरस्वती",
    "title": "जय सरस्वती माता",
    "url": "https://www.bhaktibharat.com/aarti/maa-saraswati-ji",
    "opening": "जय सरस्वती माता,",
    "id": 8,
    "lyrics": "जय सरस्वती माता,\nमैया जय सरस्वती माता ।\nसदगुण वैभव शालिनी,\nत्रिभुवन विख्याता ॥\nजय जय सरस्वती माता...॥\nचन्द्रवदनि पद्मासिनि,\nद्युति मंगलकारी ।\nसोहे शुभ हंस सवारी,\nअतुल तेजधारी ॥\nजय जय सरस्वती माता...॥\nबाएं कर में वीणा,\nदाएं कर माला ।\nशीश मुकुट मणि सोहे,\nगल मोतियन माला ॥\nजय जय सरस्वती माता...॥\nदेवी शरण जो आए,\nउनका उद्धार किया ।\nपैठी मंथरा दासी,\nरावण संहार किया ॥\nजय जय सरस्वती माता...॥\nविद्या ज्ञान प्रदायिनि,\nज्ञान प्रकाश भरो ।\nमोह अज्ञान और तिमिर का,\nजग से नाश करो ॥\nजय जय सरस्वती माता...॥\nधूप दीप फल मेवा,\nमाँ स्वीकार करो ।\nज्ञानचक्षु दे माता,\nजग निस्तार करो ॥\n॥ जय सरस्वती माता...॥\nमाँ सरस्वती की आरती,\nजो कोई जन गावे ।\nहितकारी सुखकारी,\nज्ञान भक्ति पावे ॥\nजय जय सरस्वती माता...॥\nजय सरस्वती माता,\nजय जय सरस्वती माता ।\nसदगुण वैभव शालिनी,\nत्रिभुवन विख्याता ॥",
    "romanTitle": "jay sarasvati mata",
    "romanLyrics": "jay sarasvati mata,\nmaiya jay sarasvati mata .\nsadgun vaibhav shalini,\ntribhuvan vikhyata ..\njay jay sarasvati mata.....\nchandravdani padmasini,\ndyuti maagalkari .\nsohe shubh hams savari,\natul tejdhari ..\njay jay sarasvati mata.....\nbaem kar mem vina,\ndaem kar mala .\nshish mukut mani sohe,\ngal motiyan mala ..\njay jay sarasvati mata.....\ndevi sharan jo ae,\nunka uddhar kiya .\npaithi maathra dasi,\nravan samhar kiya ..\njay jay sarasvati mata.....\nvidya jnyan pradayini,\njnyan prakash bharo .\nmoh ajnyan aur timir ka,\njag se nash karo ..\njay jay sarasvati mata.....\ndhup dip phal meva,\nmaa svikar karo .\njnyanachakshu de mata,\njag nistar karo ..\n.. jay sarasvati mata.....\nmaa sarasvati ki aarti,\njo koi jan gave .\nhitkari sukhkari,\njnyan bhakti pave ..\njay jay sarasvati mata.....\njay sarasvati mata,\njay jay sarasvati mata .\nsadgun vaibhav shalini,\ntribhuvan vikhyata .."
  },
  {
    "category": "राम",
    "title": "रघुवर श्री रामचन्द्र जी",
    "url": "https://www.bhaktibharat.com/aarti/raghuvar-shri-ramchandra-ji",
    "opening": "आरती कीजै श्री रघुवर जी की,",
    "id": 9,
    "lyrics": "आरती कीजै श्री रघुवर जी की,\nसत चित आनन्द शिव सुन्दर की॥\nदशरथ तनय कौशल्या नन्दन,\nसुर मुनि रक्षक दैत्य निकन्दन॥\nअनुगत भक्त भक्त उर चन्दन,\nमर्यादा पुरुषोत्तम वर की॥\nनिर्गुण सगुण अनूप रूप निधि,\nसकल लोक वन्दित विभिन्न विधि॥\nहरण शोक-भय दायक नव निधि,\nमाया रहित दिव्य नर वर की॥\nजानकी पति सुर अधिपति जगपति,\nअखिल लोक पालक त्रिलोक गति॥\nविश्व वन्द्य अवन्ह अमित गति,\nएक मात्र गति सचराचर की॥\nशरणागत वत्सल व्रतधारी,\nभक्त कल्प तरुवर असुरारी॥\nनाम लेत जग पावनकारी,\nवानर सखा दीन दुख हर की॥",
    "romanTitle": "raghuvar shri ramachandra ji",
    "romanLyrics": "aarti kijai shri raghuvar ji ki,\nsat chit anand shiv sundar ki..\ndashrath tanay kaushalya nandan,\nsur muni rakshak daitya nikandan..\nanugat bhakt bhakt ur chandan,\nmaryada purushottam var ki..\nnirgun sagun anup rup nidhi,\nsakal lok vandit vibhinn vidhi..\nharan shok-bhay dayak nav nidhi,\nmaya rahit divya nar var ki..\njanki pati sur adhipti jagpati,\nakhil lok palak trilok gati..\nvishva vandya avanha amit gati,\nek matra gati sacharachar ki..\nsharanagat vatsal vratdhari,\nbhakt kalp taruvar asurari..\nnam let jag pavankari,\nvanar sakha din dukh har ki.."
  },
  {
    "category": "संतोषी माता",
    "title": "जय सन्तोषी माता",
    "url": "https://www.bhaktibharat.com/aarti/jai-santoshi-mata",
    "opening": "जय सन्तोषी माता,",
    "id": 10,
    "lyrics": "जय सन्तोषी माता,\nमैया जय सन्तोषी माता ।\nअपने सेवक जन की,\nसुख सम्पति दाता ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nसुन्दर चीर सुनहरी,\nमां धारण कीन्हो ।\nहीरा पन्ना दमके,\nतन श्रृंगार लीन्हो ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nगेरू लाल छटा छबि,\nबदन कमल सोहे ।\nमंद हंसत करुणामयी,\nत्रिभुवन जन मोहे ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nस्वर्ण सिंहासन बैठी,\nचंवर दुरे प्यारे ।\nधूप, दीप, मधु, मेवा,\nभोज धरे न्यारे ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nगुड़ अरु चना परम प्रिय,\nतामें संतोष कियो ।\nसंतोषी कहलाई,\nभक्तन वैभव दियो ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nशुक्रवार प्रिय मानत,\nआज दिवस सोही ।\nभक्त मंडली छाई,\nकथा सुनत मोही ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nमंदिर जग मग ज्योति,\nमंगल ध्वनि छाई ।\nविनय करें हम सेवक,\nचरनन सिर नाई ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nभक्ति भावमय पूजा,\nअंगीकृत कीजै ।\nजो मन बसे हमारे,\nइच्छित फल दीजै ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nदुखी दारिद्री रोगी,\nसंकट मुक्त किए ।\nबहु धन धान्य भरे घर,\nसुख सौभाग्य दिए ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nध्यान धरे जो तेरा,\nवांछित फल पायो ।\nपूजा कथा श्रवण कर,\nघर आनन्द आयो ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nचरण गहे की लज्जा,\nरखियो जगदम्बे ।\nसंकट तू ही निवारे,\nदयामयी अम्बे ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\nसन्तोषी माता की आरती,\nजो कोई जन गावे ।\nरिद्धि सिद्धि सुख सम्पति,\nजी भर के पावे ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ।\nअपने सेवक जन की,\nसुख सम्पति दाता ॥",
    "romanTitle": "jay santoshi mata",
    "romanLyrics": "jay santoshi mata,\nmaiya jay santoshi mata .\napne sevak jan ki,\nsukh sampati data ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nsundar chir sunhari,\nmaa dharan kinho .\nhira panna danke,\ntan shrrimgar linho ..\njay santoshi mata,\nmaiya jay santoshi mata ..\ngeru lal chhata chhabi,\nbadan kamal sohe .\nmand hamsat karunamyi,\ntribhuvan jan mohe ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nsvarn simhasan baithi,\nchamvar dure pyare .\ndhup, dip, madhu, meva,\nbhoj dhare nyare ..\njay santoshi mata,\nmaiya jay santoshi mata ..\ngur aru chana param priy,\ntamem samtosh kiyo .\nsamtoshi kahalai,\nbhaktan vaibhav diyo ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nshukravar priy manat,\naj divas sohi .\nbhakt mandli chhai,\nkatha sunat mohi ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nmandir jag mag jyoti,\nmaagal dhvani chhai .\nvinay karen ham sevak,\ncharnan sir nai ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nbhakti bhavmay puja,\namgikrit kijai .\njo man base hamare,\nichchhit phal dijai ..\njay santoshi mata,\nmaiya jay santoshi mata ..\ndukhi daridri rogi,\nsankat mukt kie .\nbahu dhan dhanya bhare ghar,\nsukh saubhagya die ..\njay santoshi mata,\nmaiya jay santoshi mata ..\ndhyan dhare jo tera,\nvamchhit phal payo .\npuja katha shravan kar,\nghar anand ayo ..\njay santoshi mata,\nmaiya jay santoshi mata ..\ncharan gahe ki lajja,\nrakhiyo jagadambe .\nsankat tu hi nivare,\ndayamyi ambe ..\njay santoshi mata,\nmaiya jay santoshi mata ..\nsantoshi mata ki aarti,\njo koi jan gave .\nriddhi siddhi sukh sampati,\nji bhar ke pave ..\njay santoshi mata,\nmaiya jay santoshi mata .\napne sevak jan ki,\nsukh sampati data .."
  },
  {
    "category": "शनि",
    "title": "जय जय श्री शनिदेव",
    "url": "https://www.bhaktibharat.com/aarti/shri-shani-dev-ji",
    "opening": "जय जय श्री शनिदेव भक्तन हितकारी ।",
    "id": 11,
    "lyrics": "जय जय श्री शनिदेव भक्तन हितकारी ।\nसूरज के पुत्र प्रभु छाया महतारी ॥\n॥ जय जय श्री शनिदेव..॥\nश्याम अंक वक्र दृष्ट चतुर्भुजा धारी ।\nनीलाम्बर धार नाथ गज की असवारी ॥\n॥ जय जय श्री शनिदेव..॥\nक्रीट मुकुट शीश रजित दिपत है लिलारी ।\nमुक्तन की माला गले शोभित बलिहारी ॥\n॥ जय जय श्री शनिदेव..॥\nमोदक मिष्ठान पान चढ़त हैं सुपारी ।\nलोहा तिल तेल उड़द महिषी अति प्यारी ॥\n॥ जय जय श्री शनिदेव..॥\nदेव दनुज ऋषि मुनि सुमरिन नर नारी ।\nविश्वनाथ धरत ध्यान शरण हैं तुम्हारी ॥\n॥ जय जय श्री शनिदेव..॥",
    "romanTitle": "jay jay shri shanidev",
    "romanLyrics": "jay jay shri shanidev bhaktan hitkari .\nsuraj ke putra prabhu chhaya mahtari ..\n.. jay jay shri shanidev....\nshyam ank vakra drisht chaturbhuja dhari .\nnilambar dhar nath gaj ki asvari ..\n.. jay jay shri shanidev....\nkrit mukut shish rajit dipat hai lilari .\nmuktan ki mala gale shobhit balihari ..\n.. jay jay shri shanidev....\nmodak mishthan pan charhat haim supari .\nloha til tel urad mahishi ati pyari ..\n.. jay jay shri shanidev....\ndev danuj rishi muni sumrin nar nari .\nvishvanath dharat dhyan sharan haim tumhari ..\n.. jay jay shri shanidev...."
  },
  {
    "category": "सूर्य",
    "title": "ऊँ जय कश्यप नन्दन",
    "url": "https://www.bhaktibharat.com/aarti/shri-surya-dev-jai-kashyapa-nandana",
    "opening": "ऊँ जय कश्यप नन्दन, प्रभु जय अदिति नन्दन।",
    "id": 12,
    "lyrics": "ऊँ जय कश्यप नन्दन, प्रभु जय अदिति नन्दन।\nत्रिभुवन तिमिर निकंदन, भक्त हृदय चन्दन॥\n॥ ऊँ जय कश्यप...॥\nसप्त अश्वरथ राजित, एक चक्रधारी।\nदु:खहारी, सुखकारी, मानस मलहारी॥\n॥ ऊँ जय कश्यप...॥\nसुर मुनि भूसुर वन्दित, विमल विभवशाली।\nअघ-दल-दलन दिवाकर, दिव्य किरण माली॥\n॥ ऊँ जय कश्यप...॥\nसकल सुकर्म प्रसविता, सविता शुभकारी।\nविश्व विलोचन मोचन, भव-बंधन भारी॥\n॥ ऊँ जय कश्यप...॥\nकमल समूह विकासक, नाशक त्रय तापा।\nसेवत सहज हरत अति, मनसिज संतापा॥\n॥ ऊँ जय कश्यप...॥\nनेत्र व्याधि हर सुरवर, भू-पीड़ा हारी।\nवृष्टि विमोचन संतत, परहित व्रतधारी॥\n॥ ऊँ जय कश्यप...॥\nसूर्यदेव करुणाकर, अब करुणा कीजै।\nहर अज्ञान मोह सब, तत्वज्ञान दीजै॥\nऊँ जय कश्यप नन्दन, प्रभु जय अदिति नन्दन।\nत्रिभुवन तिमिर निकंदन, भक्त हृदय चन्दन॥",
    "romanTitle": "Om jay kashyap nandan",
    "romanLyrics": "Om jay kashyap nandan, prabhu jay aditi nandan.\ntribhuvan timir nikamdan, bhakt hriday chandan..\n.. Om jay kashyap.....\nsapt ashvarath rajit, ek chakradhari.\ndu:khahari, sukhkari, manas malhari..\n.. Om jay kashyap.....\nsur muni bhusur vandit, vimal vibhavshali.\nagh-dal-dalan divakar, divya kiran mali..\n.. Om jay kashyap.....\nsakal sukarm prasvita, savita shubhkari.\nvishva vilochan mochan, bhav-bandhan bhari..\n.. Om jay kashyap.....\nkamal samuh vikasak, nashak tray tapa.\nsevat sahaj harat ati, mansij samtapa..\n.. Om jay kashyap.....\nnetra vyadhi har survar, bhu-pira hari.\nvrishti vimochan samtat, parhit vratdhari..\n.. Om jay kashyap.....\nsuryadev karunakar, ab karuna kijai.\nhar ajnyan moh sab, tatvajnyan dijai..\nOm jay kashyap nandan, prabhu jay aditi nandan.\ntribhuvan timir nikamdan, bhakt hriday chandan.."
  },
  {
    "category": "सत्यनारायण",
    "title": "श्री सत्यनारायण जी",
    "url": "https://www.bhaktibharat.com/aarti/shri-satyanarayan-ji",
    "opening": "जय लक्ष्मी रमणा,",
    "id": 13,
    "lyrics": "जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nसत्यनारायण स्वामी,\nजन पातक हरणा ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nरत्‍‌न जडि़त सिंहासन,\nअद्भुत छवि राजै ।\nनारद करत निराजन,\nघण्टा ध्वनि बाजै ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nप्रकट भये कलि कारण,\nद्विज को दर्श दियो ।\nबूढ़ा ब्राह्मण बनकर,\nकंचन महल कियो ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nदुर्बल भील कठारो,\nजिन पर कृपा करी ।\nचन्द्रचूड़ एक राजा,\nतिनकी विपत्ति हरी ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nवैश्य मनोरथ पायो,\nश्रद्धा तज दीन्ही ।\nसो फल भोग्यो प्रभुजी,\nफिर-स्तुति कीन्हीं ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nभाव भक्ति के कारण,\nछिन-छिन रूप धरयो ।\nश्रद्धा धारण कीन्हीं,\nतिनको काज सरयो ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nग्वाल-बाल संग राजा,\nवन में भक्ति करी ।\nमनवांछित फल दीन्हों,\nदीनदयाल हरी ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nचढ़त प्रसाद सवायो,\nकदली फल, मेवा ।\nधूप दीप तुलसी से,\nराजी सत्यदेवा ॥\nॐ जय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nश्री सत्यनारायण जी की आरती,\nजो कोई नर गावै ।\nऋद्धि-सिद्ध सुख-संपत्ति,\nसहज रूप पावे ॥\nजय लक्ष्मी रमणा,\nस्वामी जय लक्ष्मी रमणा ।\nसत्यनारायण स्वामी,\nजन पातक हरणा ॥",
    "romanTitle": "shri satyanarayan ji",
    "romanLyrics": "jay lakshmi ramna,\nswami jay lakshmi ramna .\nsatyanarayan swami,\njan patak harna ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\nratna jadita simhasan,\nadbhut chhavi rajai .\nnarad karat nirajan,\nghanta dhvani bajai ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\nprakat bhaye kali karan,\ndvij ko darsh diyo .\nburha brahman bankar,\nkamchan mahal kiyo ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\ndurbal bhil katharo,\njin par kripa kari .\nchandrachur ek raja,\ntinki vipatti hari ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\nvaishya manorath payo,\nshraddha taj dinhi .\nso phal bhogyo prabhuji,\nphir-stuti kinhim ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\nbhav bhakti ke karan,\nchhin-chhin rup dharyo .\nshraddha dharan kinhim,\ntinko kaj saryo ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\ngval-bal samg raja,\nvan mem bhakti kari .\nmanavamchhit phal dinhom,\ndinadyal hari ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\ncharhat prasad savayo,\nkadli phal, meva .\ndhup dip tulsi se,\nraji satyadeva ..\nOm jay lakshmi ramna,\nswami jay lakshmi ramna .\nshri satyanarayan ji ki aarti,\njo koi nar gavai .\nriddhi-siddh sukh-sampatti,\nsahaj rup pave ..\njay lakshmi ramna,\nswami jay lakshmi ramna .\nsatyanarayan swami,\njan patak harna .."
  },
  {
    "category": "गंगा",
    "title": "श्री गंगा मैया",
    "url": "https://www.bhaktibharat.com/aarti/shri-ganga-maiya-ji",
    "opening": "ॐ जय गंगे माता,",
    "id": 14,
    "lyrics": "ॐ जय गंगे माता,\nश्री जय गंगे माता ।\nजो नर तुमको ध्याता,\nमनवांछित फल पाता ॥\nचंद्र सी जोत तुम्हारी,\nजल निर्मल आता ।\nशरण पडें जो तेरी,\nसो नर तर जाता ॥\n॥ ॐ जय गंगे माता..॥\nपुत्र सगर के तारे,\nसब जग को ज्ञाता ।\nकृपा दृष्टि तुम्हारी,\nत्रिभुवन सुख दाता ॥\n॥ ॐ जय गंगे माता..॥\nएक ही बार जो तेरी,\nशारणागति आता ।\nयम की त्रास मिटा कर,\nपरमगति पाता ॥\n॥ ॐ जय गंगे माता..॥\nआरती मात तुम्हारी,\nजो जन नित्य गाता ।\nदास वही सहज में,\nमुक्त्ति को पाता ॥\n॥ ॐ जय गंगे माता..॥\nॐ जय गंगे माता,\nश्री जय गंगे माता ।\nजो नर तुमको ध्याता,\nमनवांछित फल पाता ॥\nॐ जय गंगे माता,\nश्री जय गंगे माता ।",
    "romanTitle": "shri ganga maiya",
    "romanLyrics": "Om jay gange mata,\nshri jay gange mata .\njo nar tumko dhyata,\nmanavamchhit phal pata ..\nchamdra si jot tumhari,\njal nirmal ata .\nsharan padem jo teri,\nso nar tar jata ..\n.. Om jay gange mata....\nputra sagar ke tare,\nsab jag ko jnyata .\nkripa drishti tumhari,\ntribhuvan sukh data ..\n.. Om jay gange mata....\nek hi bar jo teri,\nsharanagti ata .\nyam ki tras mita kar,\nparamgati pata ..\n.. Om jay gange mata....\naarti mat tumhari,\njo jan nitya gata .\ndas vahi sahaj mem,\nmuktti ko pata ..\n.. Om jay gange mata....\nOm jay gange mata,\nshri jay gange mata .\njo nar tumko dhyata,\nmanavamchhit phal pata ..\nOm jay gange mata,\nshri jay gange mata ."
  },
  {
    "category": "तुलसी",
    "title": "जय जय तुलसी माता",
    "url": "https://www.bhaktibharat.com/aarti/jai-jai-tulsi-mata",
    "opening": "जय जय तुलसी माता,",
    "id": 15,
    "lyrics": "जय जय तुलसी माता,\nमैया जय तुलसी माता ।\nसब जग की सुख दाता,\nसबकी वर माता ॥\n॥ जय तुलसी माता...॥\nसब योगों से ऊपर,\nसब रोगों से ऊपर ।\nरज से रक्ष करके,\nसबकी भव त्राता ॥\n॥ जय तुलसी माता...॥\nबटु पुत्री है श्यामा,\nसूर बल्ली है ग्राम्या ।\nविष्णुप्रिय जो नर तुमको सेवे,\nसो नर तर जाता ॥\n॥ जय तुलसी माता...॥\nहरि के शीश विराजत,\nत्रिभुवन से हो वंदित ।\nपतित जनों की तारिणी,\nतुम हो विख्याता ॥\n॥ जय तुलसी माता...॥\nलेकर जन्म विजन में,\nआई दिव्य भवन में ।\nमानव लोक तुम्हीं से,\nसुख-संपति पाता ॥\n॥ जय तुलसी माता...॥\nहरि को तुम अति प्यारी,\nश्याम वर्ण सुकुमारी ।\nप्रेम अजब है उनका,\nतुमसे कैसा नाता ॥\nहमारी विपद हरो तुम,\nकृपा करो माता ॥\n॥ जय तुलसी माता...॥\nजय जय तुलसी माता,\nमैया जय तुलसी माता ।\nसब जग की सुख दाता,\nसबकी वर माता ॥",
    "romanTitle": "jay jay tulsi mata",
    "romanLyrics": "jay jay tulsi mata,\nmaiya jay tulsi mata .\nsab jag ki sukh data,\nsabki var mata ..\n.. jay tulsi mata.....\nsab yogOm se upar,\nsab rogOm se upar .\nraj se raksh karke,\nsabki bhav trata ..\n.. jay tulsi mata.....\nbatu putri hai shyama,\nsur balli hai gramya .\nvishnupriy jo nar tumko seve,\nso nar tar jata ..\n.. jay tulsi mata.....\nhari ke shish virajat,\ntribhuvan se ho vamdit .\npatit janOm ki tarini,\ntum ho vikhyata ..\n.. jay tulsi mata.....\nlekar janma vijan mem,\nai divya bhavan mem .\nmanav lok tumhim se,\nsukh-sampti pata ..\n.. jay tulsi mata.....\nhari ko tum ati pyari,\nshyam varn sukumari .\nprem ajab hai unka,\ntumse kaisa nata ..\nhamari vipad haro tum,\nkripa karo mata ..\n.. jay tulsi mata.....\njay jay tulsi mata,\nmaiya jay tulsi mata .\nsab jag ki sukh data,\nsabki var mata .."
  },
  {
    "category": "विश्वकर्मा",
    "title": "श्री विश्वकर्मा जी",
    "url": "https://www.bhaktibharat.com/aarti/shri-vishwakarma-ji-ki-aarti",
    "opening": "जय श्री विश्वकर्मा प्रभु,",
    "id": 16,
    "lyrics": "जय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nसकल सृष्टि के करता,\nरक्षक स्तुति धर्मा ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nआदि सृष्टि मे विधि को,\nश्रुति उपदेश दिया ।\nजीव मात्र का जग में,\nज्ञान विकास किया ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nऋषि अंगीरा तप से,\nशांति नहीं पाई ।\nध्यान किया जब प्रभु का,\nसकल सिद्धि आई ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nरोग ग्रस्त राजा ने,\nजब आश्रय लीना ।\nसंकट मोचन बनकर,\nदूर दुःखा कीना ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nजब रथकार दंपति,\nतुम्हारी टेर करी ।\nसुनकर दीन प्रार्थना,\nविपत सगरी हरी ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nएकानन चतुरानन,\nपंचानन राजे।\nत्रिभुज चतुर्भुज दशभुज,\nसकल रूप साजे ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nध्यान धरे तब पद का,\nसकल सिद्धि आवे ।\nमन द्विविधा मिट जावे,\nअटल शक्ति पावे ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nश्री विश्वकर्मा की आरती,\nजो कोई गावे ।\nभजत गजानांद स्वामी,\nसुख संपति पावे ॥\nजय श्री विश्वकर्मा प्रभु,\nजय श्री विश्वकर्मा ।\nसकल सृष्टि के करता,\nरक्षक स्तुति धर्मा ॥",
    "romanTitle": "shri vishvakarma ji",
    "romanLyrics": "jay shri vishvakarma prabhu,\njay shri vishvakarma .\nsakal srishti ke karta,\nrakshak stuti dharma ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nadi srishti me vidhi ko,\nshruti updesh diya .\njiv matra ka jag mem,\njnyan vikas kiya ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nrishi amgira tap se,\nshamti nahim pai .\ndhyan kiya jab prabhu ka,\nsakal siddhi ai ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nrog grast raja ne,\njab ashray lina .\nsankat mochan bankar,\ndur duhkha kina ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\njab rathkar dampti,\ntumhari ter kari .\nsunkar din prarthana,\nvipat sagri hari ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nekanan chaturanan,\npamchanan raje.\ntribhuj chaturbhuj dashbhuj,\nsakal rup saje ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\ndhyan dhare tab pad ka,\nsakal siddhi ave .\nman dvividha mit jave,\natal shakti pave ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nshri vishvakarma ki aarti,\njo koi gave .\nbhajat gajanamd swami,\nsukh sampti pave ..\njay shri vishvakarma prabhu,\njay shri vishvakarma .\nsakal srishti ke karta,\nrakshak stuti dharma .."
  },
  {
    "category": "पार्वती",
    "title": "माता पार्वती",
    "url": "https://www.bhaktibharat.com/aarti/shri-parvati-maa",
    "opening": "जय पार्वती माता,",
    "id": 17,
    "lyrics": "जय पार्वती माता,\nजय पार्वती माता\nब्रह्मा सनातन देवी,\nशुभ फल की दाता ।\n॥ जय पार्वती माता... ॥\nअरिकुल कंटक नासनि,\nनिज सेवक त्राता,\nजगजननी जगदम्बा,\nहरिहर गुण गाता ।\n॥ जय पार्वती माता... ॥\nसिंह को वहान साजे,\nकुंडल है साथा,\nदेव वधू जस गावत,\nनृत्य करत ता था ।\n॥ जय पार्वती माता... ॥\nसतयुग रूप शील अतिसुंदर,\nनाम सती कहलाता,\nहेमाचंल घर जन्मी,\nसखियाँ संगराता ।\n॥ जय पार्वती माता... ॥\nशुम्भ निशुम्भ विदारे,\nहेमाचंल स्थाता,\nसहस्त्र भुजा तनु धरिके,\nचक्र लियो हाथा ।\n॥ जय पार्वती माता... ॥\nसृष्टि रूप तुही है जननी,\nशिव संग रंगराता,\nनन्दी भृंगी बीन लही,\nसारा जग मदमाता ।\n॥ जय पार्वती माता... ॥\nदेवन अरज करत हम,\nचरण ध्यान लाता,\nतेरी कृपा रहे तो,\nमन नहीं भरमाता ।\n॥ जय पार्वती माता... ॥\nमैया जी की आरती,\nभक्ति भाव से जो नर गाता,\nनित्य सुखी रह करके,\nसुख संपत्ति पाता ।\n॥ जय पार्वती माता... ॥\nजय पार्वती माता,\nजय पार्वती माता,\nब्रह्मा सनातन देवी,\nशुभ फल की दाता ।\nजय पार्वती माता,\nजय पार्वती माता\nब्रह्मा सनातन देवी,\nशुभ फल की दाता ।",
    "romanTitle": "mata parvati",
    "romanLyrics": "jay parvati mata,\njay parvati mata\nbrahma sanatan devi,\nshubh phal ki data .\n.. jay parvati mata... ..\narikul kamtak nasni,\nnij sevak trata,\njagajnani jagadamba,\nharihar gun gata .\n.. jay parvati mata... ..\nsimh ko vahan saje,\nkumdal hai satha,\ndev vadhu jas gavat,\nnritya karat ta tha .\n.. jay parvati mata... ..\nsatyug rup shil atisumdar,\nnam sati kahlata,\nhemachaml ghar janmi,\nsakhiyam samgrata .\n.. jay parvati mata... ..\nshumbh nishumbh vidare,\nhemachaml sthata,\nsahastra bhuja tanu dharike,\nchakra liyo hatha .\n.. jay parvati mata... ..\nsrishti rup tuhi hai janni,\nshiv samg ramgrata,\nnandi bhrimgi bin lahi,\nsara jag madmata .\n.. jay parvati mata... ..\ndevan araj karat ham,\ncharan dhyan lata,\nteri kripa rahe to,\nman nahim bharmata .\n.. jay parvati mata... ..\nmaiya ji ki aarti,\nbhakti bhav se jo nar gata,\nnitya sukhi rah karke,\nsukh sampatti pata .\n.. jay parvati mata... ..\njay parvati mata,\njay parvati mata,\nbrahma sanatan devi,\nshubh phal ki data .\njay parvati mata,\njay parvati mata\nbrahma sanatan devi,\nshubh phal ki data ."
  },
  {
    "category": "गायत्री",
    "title": "माता गायत्री",
    "url": "https://www.bhaktibharat.com/aarti/gayatri-mata-ki-arti",
    "opening": "जयति जय गायत्री माता,",
    "id": 18,
    "lyrics": "जयति जय गायत्री माता,\nजयति जय गायत्री माता ।\nसत् मारग पर हमें चलाओ,\nजो है सुखदाता ॥\n॥ जयति जय गायत्री माता..॥\nआदि शक्ति तुम अलख निरंजन जगपालक क‌र्त्री ।\nदु:ख शोक, भय, क्लेश कलश दारिद्र दैन्य हत्री ॥\n॥ जयति जय गायत्री माता..॥\nब्रह्म रूपिणी, प्रणात पालिन जगत धातृ अम्बे ।\nभव भयहारी, जन-हितकारी, सुखदा जगदम्बे ॥\n॥ जयति जय गायत्री माता..॥\nभय हारिणी, भवतारिणी, अनघेअज आनन्द राशि ।\nअविकारी, अखहरी, अविचलित, अमले, अविनाशी ॥\n॥ जयति जय गायत्री माता..॥\nकामधेनु सतचित आनन्द जय गंगा गीता ।\nसविता की शाश्वती, शक्ति तुम सावित्री सीता ॥\n॥ जयति जय गायत्री माता..॥\nऋग, यजु साम, अथर्व प्रणयनी, प्रणव महामहिमे ।\nकुण्डलिनी सहस्त्र सुषुमन शोभा गुण गरिमे ॥\n॥ जयति जय गायत्री माता..॥\nस्वाहा, स्वधा, शची ब्रह्माणी राधा रुद्राणी ।\nजय सतरूपा, वाणी, विद्या, कमला कल्याणी ॥\n॥ जयति जय गायत्री माता..॥\nजननी हम हैं दीन-हीन, दु:ख-दरिद्र के घेरे ।\nयदपि कुटिल, कपटी कपूत तउ बालक हैं तेरे ॥\n॥ जयति जय गायत्री माता..॥\nस्नेहसनी करुणामय माता चरण शरण दीजै ।\nविलख रहे हम शिशु सुत तेरे दया दृष्टि कीजै ॥\n॥ जयति जय गायत्री माता..॥\nकाम, क्रोध, मद, लोभ, दम्भ, दुर्भाव द्वेष हरिये ।\nशुद्ध बुद्धि निष्पाप हृदय मन को पवित्र करिये ॥\n॥ जयति जय गायत्री माता..॥\nजयति जय गायत्री माता,\nजयति जय गायत्री माता ।\nसत् मारग पर हमें चलाओ,\nजो है सुखदाता ॥",
    "romanTitle": "mata gayatri",
    "romanLyrics": "jayati jay gayatri mata,\njayati jay gayatri mata .\nsat marag par hamem chalao,\njo hai sukhdata ..\n.. jayati jay gayatri mata....\nadi shakti tum alakh niramjan jagapalak kartri .\ndu:kha shok, bhay, klesh kalash daridra dainya hatri ..\n.. jayati jay gayatri mata....\nbrahma rupini, pranat palin jagat dhatri ambe .\nbhav bhayhari, jan-hitkari, sukhda jagadambe ..\n.. jayati jay gayatri mata....\nbhay harini, bhavatarini, anagheaj anand rashi .\navikari, akhhari, avichlit, amle, avinashi ..\n.. jayati jay gayatri mata....\nkamdhenu satchit anand jay ganga gita .\nsavita ki shashvati, shakti tum savitri sita ..\n.. jayati jay gayatri mata....\nrig, yaju sam, atharva pranyani, pranav mahamhime .\nkundalini sahastra sushuman shobha gun garime ..\n.. jayati jay gayatri mata....\nsvaha, svadha, shachi brahmani radha rudrani .\njay satrupa, vani, vidya, kamla kalyani ..\n.. jayati jay gayatri mata....\njanni ham haim din-hin, du:kha-daridra ke ghere .\nyadpi kutil, kapti kaput tau balak haim tere ..\n.. jayati jay gayatri mata....\nsnehsani karunamay mata charan sharan dijai .\nvilakh rahe ham shishu sut tere daya drishti kijai ..\n.. jayati jay gayatri mata....\nkam, krodh, mad, lobh, dambh, durbhav dvesh hariye .\nshuddh buddhi nishpap hriday man ko pavitra kariye ..\n.. jayati jay gayatri mata....\njayati jay gayatri mata,\njayati jay gayatri mata .\nsat marag par hamem chalao,\njo hai sukhdata .."
  },
  {
    "id": 19,
    "category": "बृहस्पति",
    "title": "बृहस्पति देव की आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-brihaspati-dev-ji-ki-aarti-in-hindi",
    "lyrics": "ऊँ जय वृहस्पति देवा ।\nछिन छिन भोग लगा‌ऊँ,\nकदली फल मेवा ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nतुम पूरण परमात्मा,\nतुम अन्तर्यामी ।\nजगतपिता जगदीश्वर,\nतुम सबके स्वामी ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nचरणामृत निज निर्मल,\nसब पातक हर्ता ।\nसकल मनोरथ दायक,\nकृपा करो भर्ता ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nतन, मन, धन अर्पण कर,\nजो जन शरण पड़े ।\nप्रभु प्रकट तब होकर,\nआकर द्घार खड़े ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nदीनदयाल दयानिधि,\nभक्तन हितकारी ।\nपाप दोष सब हर्ता,\nभव बंधन हारी ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nसकल मनोरथ दायक,\nसब संशय हारो ।\nविषय विकार मिटा‌ओ,\nसंतन सुखकारी ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nजो को‌ई आरती तेरी,\nप्रेम सहित गावे ।\nजेठानन्द आनन्दकर,\nसो निश्चय पावे ॥\nऊँ जय वृहस्पति देवा,\nजय वृहस्पति देवा ॥\nसब बोलो विष्णु भगवान की जय ।\nबोलो वृहस्पतिदेव भगवान की जय ॥",
    "opening": "ऊँ जय वृहस्पति देवा ।",
    "romanTitle": "brihaspati dev ki aarti",
    "romanLyrics": "Om jay vrihaspati deva .\nchhin chhin bhog lagaum,\nkadli phal meva ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\ntum puran paramatma,\ntum antaryami .\njagatpita jagadishvar,\ntum sabke swami ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\ncharanamrit nij nirmal,\nsab patak harta .\nsakal manorath dayak,\nkripa karo bharta ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\ntan, man, dhan arpan kar,\njo jan sharan pare .\nprabhu prakat tab hokar,\nakar dghar khare ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\ndinadyal dayanidhi,\nbhaktan hitkari .\npap dosh sab harta,\nbhav bandhan hari ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\nsakal manorath dayak,\nsab samshay haro .\nvishay vikar mitao,\nsamtan sukhkari ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\njo koi aarti teri,\nprem sahit gave .\njethanand anandakar,\nso nishchay pave ..\nOm jay vrihaspati deva,\njay vrihaspati deva ..\nsab bolo vishnu bhagvan ki jay .\nbolo vrihaspatidev bhagvan ki jay .."
  },
  {
    "id": 20,
    "category": "बालाजी",
    "title": "श्री बालाजी आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-balaji",
    "lyrics": "ॐ जय हनुमत वीरा,\nस्वामी जय हनुमत वीरा ।\nसंकट मोचन स्वामी,\nतुम हो रनधीरा ॥\n॥ ॐ जय हनुमत वीरा..॥\nपवन पुत्र अंजनी सूत,\nमहिमा अति भारी ।\nदुःख दरिद्र मिटाओ,\nसंकट सब हारी ॥\n॥ ॐ जय हनुमत वीरा..॥\nबाल समय में तुमने,\nरवि को भक्ष लियो ।\nदेवन स्तुति किन्ही,\nतुरतहिं छोड़ दियो ॥\n॥ ॐ जय हनुमत वीरा..॥\nकपि सुग्रीव राम संग,\nमैत्री करवाई।\nअभिमानी बलि मेटयो,\nकीर्ति रही छाई ॥\n॥ ॐ जय हनुमत वीरा..॥\nजारि लंक सिय-सुधि ले आए,\nवानर हर्षाये ।\nकारज कठिन सुधारे,\nरघुबर मन भाये ॥\n॥ ॐ जय हनुमत वीरा..॥\nशक्ति लगी लक्ष्मण को,\nभारी सोच भयो ।\nलाय संजीवन बूटी,\nदुःख सब दूर कियो ॥\n॥ ॐ जय हनुमत वीरा..॥\nरामहि ले अहिरावण,\nजब पाताल गयो ।\nताहि मारी प्रभु लाय,\nजय जयकार भयो ॥\n॥ ॐ जय हनुमत वीरा..॥\nराजत मेहंदीपुर में,\nदर्शन सुखकारी ।\nमंगल और शनिश्चर,\nमेला है जारी ॥\n॥ ॐ जय हनुमत वीरा..॥\nश्री बालाजी की आरती,\nजो कोई नर गावे ।\nकहत इन्द्र हर्षित,\nमनवांछित फल पावे ॥\n॥ ॐ जय हनुमत वीरा..॥",
    "opening": "ॐ जय हनुमत वीरा,",
    "romanTitle": "shri balaji aarti",
    "romanLyrics": "Om jay hanumat vira,\nswami jay hanumat vira .\nsankat mochan swami,\ntum ho randhira ..\n.. Om jay hanumat vira....\npavan putra amjni sut,\nmahima ati bhari .\nduhkh daridra mitao,\nsankat sab hari ..\n.. Om jay hanumat vira....\nbal samay mem tumne,\nravi ko bhaksh liyo .\ndevan stuti kinhi,\nturtahim chhor diyo ..\n.. Om jay hanumat vira....\nkapi sugriv ram samg,\nmaitri karavai.\nabhimani bali metyo,\nkirti rahi chhai ..\n.. Om jay hanumat vira....\njari lank siy-sudhi le ae,\nvanar harshaye .\nkaraj kathin sudhare,\nraghubar man bhaye ..\n.. Om jay hanumat vira....\nshakti lagi lakshman ko,\nbhari soch bhayo .\nlay samjivan buti,\nduhkh sab dur kiyo ..\n.. Om jay hanumat vira....\nramhi le ahiravan,\njab patal gayo .\ntahi mari prabhu lay,\njay jaykar bhayo ..\n.. Om jay hanumat vira....\nrajat mehamdipur mem,\ndarshan sukhkari .\nmaagal aur shanishchar,\nmela hai jari ..\n.. Om jay hanumat vira....\nshri balaji ki aarti,\njo koi nar gave .\nkahat indra harshit,\nmanavamchhit phal pave ..\n.. Om jay hanumat vira...."
  },
  {
    "id": 21,
    "category": "राधा",
    "title": "राधा रानी आरती",
    "url": "https://www.bhaktibharat.com/aarti/radha-rani-ji-ki-aarti",
    "lyrics": "आरती श्री वृषभानुसुता की,\nमंजुल मूर्ति मोहन ममता की ॥\nत्रिविध तापयुत संसृति नाशिनि,\nविमल विवेकविराग विकासिनि ।\nपावन प्रभु पद प्रीति प्रकाशिनि,\nसुन्दरतम छवि सुन्दरता की ॥\n॥ आरती श्री वृषभानुसुता की..॥\nमुनि मन मोहन मोहन मोहनि,\nमधुर मनोहर मूरति सोहनि ।\nअविरलप्रेम अमिय रस दोहनि,\nप्रिय अति सदा सखी ललिता की ॥\n॥ आरती श्री वृषभानुसुता की..॥\nसंतत सेव्य सत मुनि जनकी,\nआकर अमित दिव्यगुन गनकी ।\nआकर्षिणी कृष्ण तन मनकी,\nअति अमूल्य सम्पति समता की ॥\n॥ आरती श्री वृषभानुसुता की..॥\n। आरती श्री वृषभानुसुता की ।\nकृष्णात्मिका, कृष्ण सहचारिणि,\nचिन्मयवृन्दा विपिन विहारिणि ।\nजगजननि जग दुखनिवारिणि,\nआदि अनादिशक्ति विभुता की ॥\n॥ आरती श्री वृषभानुसुता की..॥\nआरती श्री वृषभानुसुता की,\nमंजुल मूर्ति मोहन ममता की ॥",
    "opening": "आरती श्री वृषभानुसुता की,",
    "romanTitle": "radha rani aarti",
    "romanLyrics": "aarti shri vrishabhanusuta ki,\nmaajul murti mohan mata ki ..\ntrividh tapyut samsriti nashini,\nvimal vivekavirag vikasini .\npavan prabhu pad priti prakashini,\nsundartam chhavi sundarta ki ..\n.. aarti shri vrishabhanusuta ki....\nmuni man mohan mohan mohni,\nmadhur manohar murti sohni .\naviralaprem amiy ras dohni,\npriy ati sada sakhi lalita ki ..\n.. aarti shri vrishabhanusuta ki....\nsamtat sevya sat muni janki,\nakar amit divyagun ganki .\nakarshini krishna tan manki,\nati amulya sampati samta ki ..\n.. aarti shri vrishabhanusuta ki....\n. aarti shri vrishabhanusuta ki .\nkrishnatmika, krishna sahacharini,\nchinmayavrinda vipin viharini .\njagajnani jag dukhanivarini,\nadi anadishakti vibhuta ki ..\n.. aarti shri vrishabhanusuta ki....\naarti shri vrishabhanusuta ki,\nmaajul murti mohan mata ki .."
  },
  {
    "id": 22,
    "category": "गणेश",
    "title": "शेंदुर लाल चढ़ायो",
    "url": "https://www.bhaktibharat.com/aarti/shri-ganesh-shendur-laal-chadhayo",
    "lyrics": "शेंदुर लाल चढ़ायो अच्छा गजमुखको ।\nदोंदिल लाल बिराजे सुत गौरिहरको ।\nहाथ लिए गुडलद्दु सांई सुरवरको ।\nमहिमा कहे न जाय लागत हूं पादको ॥\nजय देव जय देव..जय देव जय देव,\nजय जय श्री गणराज\nविद्या सुखदाता\nधन्य तुम्हारा दर्शन\nमेरा मन रमता,\nजय देव जय देव ॥\nअष्टौ सिद्धि दासी संकटको बैरि ।\nविघ्नविनाशन मंगल मूरत अधिकारी ।\nकोटीसूरजप्रकाश ऐबी छबि तेरी ।\nगंडस्थलमदमस्तक झूले शशिबिहारि ॥\nजय देव जय देव..\nजय देव जय देव,\nजय जय श्री गणराज\nविद्या सुखदाता\nधन्य तुम्हारा दर्शन\nमेरा मन रमता,\nजय देव जय देव ॥\nभावभगत से कोई शरणागत आवे ।\nसंतत संपत सबही भरपूर पावे ।\nऐसे तुम महाराज मोको अति भावे ।\nगोसावीनंदन निशिदिन गुन गावे ॥\nजय देव जय देव,\nजय जय श्री गणराज\nविद्या सुखदाता\nधन्य तुम्हारा दर्शन\nमेरा मन रमता,\nजय देव जय देव ॥",
    "opening": "शेंदुर लाल चढ़ायो अच्छा गजमुखको ।",
    "romanTitle": "shendur lal chadhayo",
    "romanLyrics": "shendur lal chadhayo achchha gajmukh ko .\ndomdil lal biraje sut gaurihrako .\nhath lie gudaladdu sami suravrako .\nmahima kahe na jay lagat hum padko ..\njay dev jay dev..jay dev jay dev,\njay jay shri ganraj\nvidya sukhdata\ndhanya tumhara darshan\nmera man ramta,\njay dev jay dev ..\nashtau siddhi dasi sanktako bairi .\nvighnavinashan maagal murat adhikari .\nkotisurajaprakash aibi chhabi teri .\ngamdasthalamadamastak jhule shashibihari ..\njay dev jay dev..\njay dev jay dev,\njay jay shri ganraj\nvidya sukhdata\ndhanya tumhara darshan\nmera man ramta,\njay dev jay dev ..\nbhavabhgat se koi sharanagat ave .\nsamtat sampat sabhi bharpur pave .\naise tum maharaj moko ati bhave .\ngosavinamdan nishidin gun gave ..\njay dev jay dev,\njay jay shri ganraj\nvidya sukhdata\ndhanya tumhara darshan\nmera man ramta,\njay dev jay dev .."
  },
  {
    "id": 23,
    "category": "गौ माता",
    "title": "गौ माता आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-gaumata-ji-ki-aarti",
    "lyrics": "आरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥\nअर्थकाम सद्धर्म प्रदायिनि,\nअविचल अमल मुक्तिपददायिनि ।\nसुर मानव सौभाग्य विधायिनि,\nप्यारी पूज्य नंद छैय्या की ॥\nआरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥\nअख़िल विश्‍व प्रतिपालिनी माता,\nमधुर अमिय दुग्धान्न प्रदाता ।\nरोग शोक संकट परित्राता,\nभवसागर हित दृढ़ नैय्या की ॥\nआरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥\nआयु ओज आरोग्य विकाशिनि,\nदुख दैन्य दारिद्रय विनाशिनि ।\nसुष्मा सौख्य समृद्धि प्रकाशिनि,\nविमल विवेक बुद्धि दैय्या की ॥\nआरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥\nसेवक जो चाहे दुखदाई,\nसम पय सुधा पियावति माई ।\nशत्रु मित्र सबको दुखदायी,\nस्नेह स्वभाव विश्‍व जैय्या की ॥\nआरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥\nआरती श्री गैय्या मैंय्या की,\nआरती हरनि विश्‍व धैय्या की ॥",
    "opening": "आरती श्री गैय्या मैंय्या की,",
    "romanTitle": "gau mata aarti",
    "romanLyrics": "aarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki ..\narthakam saddhrma pradayini,\navichal amal muktipadadayini .\nsur manav saubhagya vidhayini,\npyari pujya namd chhaiyya ki ..\naarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki ..\nakhil vishva pratipalini mata,\nmadhur amiy dugdhann pradata .\nrog shok sankat paritrata,\nbhavasagar hit drirh naiyya ki ..\naarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki ..\nayu oj arogya vikashini,\ndukh dainya daridray vinashini .\nsushma saukhya samriddhi prakashini,\nvimal vivek buddhi daiyya ki ..\naarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki ..\nsevak jo chahe dukhadai,\nsam pay sudha piyavti mai .\nshatru mitra sabko dukhdayi,\nsneh svabhav vishva jaiyya ki ..\naarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki ..\naarti shri gaiyya maiya ki,\naarti harni vishva dhaiyya ki .."
  },
  {
    "id": 24,
    "category": "तुलसी",
    "title": "तुलसी महारानी नमो नमो",
    "url": "https://www.bhaktibharat.com/aarti/tulsi-maharani-namo-namo",
    "lyrics": "तुलसी महारानी नमो-नमो,\nहरि की पटरानी नमो-नमो ।\nधन तुलसी पूरण तप कीनो,\nशालिग्राम बनी पटरानी ।\nजाके पत्र मंजरी कोमल,\nश्रीपति कमल चरण लपटानी ॥\nतुलसी महारानी नमो-नमो,\nहरि की पटरानी नमो-नमो ।\nधूप-दीप-नवैद्य आरती,\nपुष्पन की वर्षा बरसानी ।\nछप्पन भोग छत्तीसों व्यंजन,\nबिन तुलसी हरि एक ना मानी ॥\nतुलसी महारानी नमो-नमो,\nहरि की पटरानी नमो-नमो ।\nसभी सखी मैया तेरो यश गावें,\nभक्तिदान दीजै महारानी ।\nनमो-नमो तुलसी महारानी,\nतुलसी महारानी नमो-नमो ॥\nतुलसी महारानी नमो-नमो,\nहरि की पटरानी नमो-नमो ।",
    "opening": "तुलसी महारानी नमो-नमो,",
    "romanTitle": "tulsi maharani namo namo",
    "romanLyrics": "tulsi maharani namo-namo,\nhari ki patrani namo-namo .\ndhan tulsi puran tap kino,\nshaligram bani patrani .\njake patra maajri komal,\nshripti kamal charan laptani ..\ntulsi maharani namo-namo,\nhari ki patrani namo-namo .\ndhup-dip-navaidya aarti,\npushpan ki varsha barsani .\nchhappan bhog chhattisom vyamjan,\nbin tulsi hari ek na mani ..\ntulsi maharani namo-namo,\nhari ki patrani namo-namo .\nsabhi sakhi maiya tero yash gavem,\nbhaktidan dijai maharani .\nnamo-namo tulsi maharani,\ntulsi maharani namo-namo ..\ntulsi maharani namo-namo,\nhari ki patrani namo-namo ."
  },
  {
    "id": 25,
    "category": "वैष्णो माता",
    "title": "वैष्णो माता आरती",
    "url": "https://www.bhaktibharat.com/aarti/vaishno-mata",
    "lyrics": "जय वैष्णवी माता,\nमैया जय वैष्णवी माता ।\nहाथ जोड़ तेरे आगे,\nआरती मैं गाता ॥\n॥ जय वैष्णवी माता..॥\nशीश पे छत्र विराजे,\nमूरतिया प्यारी ।\nगंगा बहती चरनन,\nज्योति जगे न्यारी ॥\n॥ जय वैष्णवी माता..॥\nब्रह्मा वेद पढ़े नित द्वारे,\nशंकर ध्यान धरे ।\nसेवक चंवर डुलावत,\nनारद नृत्य करे ॥\n॥ जय वैष्णवी माता..॥\nसुन्दर गुफा तुम्हारी,\nमन को अति भावे ।\nबार-बार देखन को,\nऐ माँ मन चावे ॥\n॥ जय वैष्णवी माता..॥\nभवन पे झण्डे झूलें,\nघंटा ध्वनि बाजे ।\nऊँचा पर्वत तेरा,\nमाता प्रिय लागे ॥\n॥ जय वैष्णवी माता..॥\nपान सुपारी ध्वजा नारियल,\nभेंट पुष्प मेवा ।\nदास खड़े चरणों में,\nदर्शन दो देवा ॥\n॥ जय वैष्णवी माता..॥\nजो जन निश्चय करके,\nद्वार तेरे आवे ।\nउसकी इच्छा पूरण,\nमाता हो जावे ॥\n॥ जय वैष्णवी माता..॥\nइतनी स्तुति निश-दिन,\nजो नर भी गावे ।\nकहते सेवक ध्यानू,\nसुख सम्पत्ति पावे ॥\nजय वैष्णवी माता,\nमैया जय वैष्णवी माता ।\nहाथ जोड़ तेरे आगे,\nआरती मैं गाता ॥",
    "opening": "जय वैष्णवी माता,",
    "romanTitle": "vaishno mata aarti",
    "romanLyrics": "jay vaishnavi mata,\nmaiya jay vaishnavi mata .\nhath jor tere age,\naarti maim gata ..\n.. jay vaishnavi mata....\nshish pe chhatra viraje,\nmurtiya pyari .\nganga bahti charnan,\njyoti jage nyari ..\n.. jay vaishnavi mata....\nbrahma ved parhe nit dvare,\nshankar dhyan dhare .\nsevak chamvar dulavat,\nnarad nritya kare ..\n.. jay vaishnavi mata....\nsundar gupha tumhari,\nman ko ati bhave .\nbar-bar dekhan ko,\nai maa man chave ..\n.. jay vaishnavi mata....\nbhavan pe jhande jhulem,\nghamta dhvani baje .\numcha parvat tera,\nmata priy lage ..\n.. jay vaishnavi mata....\npan supari dhvaja nariyal,\nbhemt pushp meva .\ndas khare charnOm mem,\ndarshan do deva ..\n.. jay vaishnavi mata....\njo jan nishchay karke,\ndvar tere ave .\nuski ichchha puran,\nmata ho jave ..\n.. jay vaishnavi mata....\nitni stuti nish-din,\njo nar bhi gave .\nkahte sevak dhyanu,\nsukh sampatti pave ..\njay vaishnavi mata,\nmaiya jay vaishnavi mata .\nhath jor tere age,\naarti maim gata .."
  },
  {
    "id": 26,
    "category": "बद्रीनाथ",
    "title": "श्री बद्रीनाथ आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-badrinath-aarti",
    "lyrics": "पवन मंद सुगंध शीतल,\nहेम मंदिर शोभितम् ।\nनिकट गंगा बहत निर्मल,\nश्री बद्रीनाथ विश्व्म्भरम् ॥\nशेष सुमिरन करत निशदिन,\nधरत ध्यान महेश्वरम् ।\nवेद ब्रह्मा करत स्तुति,\nश्री बद्रीनाथ विश्वम्भरम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nशक्ति गौरी गणेश शारद,\nनारद मुनि उच्चारणम् ।\nजोग ध्यान अपार लीला,\nश्री बद्रीनाथ विश्व्म्भरम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nइंद्र चंद्र कुबेर धुनि कर,\nधूप दीप प्रकाशितम् ।\nसिद्ध मुनिजन करत जय जय,\nबद्रीनाथ विश्व्म्भरम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nयक्ष किन्नर करत कौतुक,\nज्ञान गंधर्व प्रकाशितम् ।\nश्री लक्ष्मी कमला चंवरडोल,\nश्री बद्रीनाथ विश्व्म्भरम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nकैलाश में एक देव निरंजन,\nशैल शिखर महेश्वरम् ।\nराजयुधिष्ठिर करत स्तुति,\nश्री बद्रीनाथ विश्व्म्भरम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nश्री बद्रजी के पंच रत्न,\nपढ्त पाप विनाशनम् ।\nकोटि तीर्थ भवेत पुण्य,\nप्राप्यते फलदायकम् ॥\n॥ पवन मंद सुगंध शीतल...॥\nपवन मंद सुगंध शीतल,\nहेम मंदिर शोभितम् ।\nनिकट गंगा बहत निर्मल,\nश्री बद्रीनाथ विश्व्म्भरम् ॥",
    "opening": "पवन मंद सुगंध शीतल,",
    "romanTitle": "shri badrinath aarti",
    "romanLyrics": "pavan mand sugandh shital,\nhem mandir shobhitam .\nnikat ganga bahat nirmal,\nshri badrinath vishvmbharam ..\nshesh sumiran karat nishdin,\ndharat dhyan maheshvaram .\nved brahma karat stuti,\nshri badrinath vishvambharam ..\n.. pavan mand sugandh shital.....\nshakti gauri ganesh sharad,\nnarad muni uchcharanam .\njog dhyan apar lila,\nshri badrinath vishvmbharam ..\n.. pavan mand sugandh shital.....\nimdra chamdra kuber dhuni kar,\ndhup dip prakashitam .\nsiddh munijan karat jay jay,\nbadrinath vishvmbharam ..\n.. pavan mand sugandh shital.....\nyaksh kinnar karat kautuk,\njnyan gamdharva prakashitam .\nshri lakshmi kamla chamvardol,\nshri badrinath vishvmbharam ..\n.. pavan mand sugandh shital.....\nkailash mem ek dev niramjan,\nshail shikhar maheshvaram .\nrajayudhishthir karat stuti,\nshri badrinath vishvmbharam ..\n.. pavan mand sugandh shital.....\nshri badraji ke pamch ratna,\npadhta pap vinashanam .\nkoti tirth bhavet punya,\nprapyate phaladayakam ..\n.. pavan mand sugandh shital.....\npavan mand sugandh shital,\nhem mandir shobhitam .\nnikat ganga bahat nirmal,\nshri badrinath vishvmbharam .."
  },
  {
    "id": 27,
    "category": "रामायण",
    "title": "श्री रामायण जी की आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-ramayan-ji",
    "lyrics": "आरती श्री रामायण जी की ।\nकीरति कलित ललित सिय पी की ॥\nगावत ब्रहमादिक मुनि नारद ।\nबाल्मीकि बिग्यान बिसारद ॥\nशुक सनकादिक शेष अरु शारद ।\nबरनि पवनसुत कीरति नीकी ॥\n॥ आरती श्री रामायण जी की..॥\nगावत बेद पुरान अष्टदस ।\nछओं शास्त्र सब ग्रंथन को रस ॥\nमुनि जन धन संतान को सरबस ।\nसार अंश सम्मत सब ही की ॥\n॥ आरती श्री रामायण जी की..॥\nगावत संतत शंभु भवानी ।\nअरु घटसंभव मुनि बिग्यानी ॥\nब्यास आदि कबिबर्ज बखानी ।\nकागभुशुंडि गरुड़ के ही की ॥\n॥ आरती श्री रामायण जी की..॥\nकलिमल हरनि बिषय रस फीकी ।\nसुभग सिंगार मुक्ति जुबती की ॥\nदलनि रोग भव मूरि अमी की ।\nतात मातु सब बिधि तुलसी की ॥\nआरती श्री रामायण जी की ।\nकीरति कलित ललित सिय पी की ॥",
    "opening": "आरती श्री रामायण जी की ।",
    "romanTitle": "shri ramayan ji ki aarti",
    "romanLyrics": "aarti shri ramayan ji ki .\nkirti kalit lalit siy pi ki ..\ngavat brahamadik muni narad .\nbalmiki bigyan bisarad ..\nshuk sanakadik shesh aru sharad .\nbarni pavansut kirti niki ..\n.. aarti shri ramayan ji ki....\ngavat bed puran ashtadas .\nchhaOm shastra sab gramthan ko ras ..\nmuni jan dhan samtan ko sarbas .\nsar amsh sammat sab hi ki ..\n.. aarti shri ramayan ji ki....\ngavat samtat shambhu bhavani .\naru ghatasambhav muni bigyani ..\nbyas adi kabibarj bakhani .\nkagabhushumdi garur ke hi ki ..\n.. aarti shri ramayan ji ki....\nkalimal harni bishay ras phiki .\nsubhag simgar mukti jubti ki ..\ndalni rog bhav muri ami ki .\ntat matu sab bidhi tulsi ki ..\naarti shri ramayan ji ki .\nkirti kalit lalit siy pi ki .."
  },
  {
    "id": 28,
    "category": "शीतला माता",
    "title": "शीतला माता आरती",
    "url": "https://www.bhaktibharat.com/aarti/sheetla-mata-ki-aarti",
    "lyrics": "जय शीतला माता,\nमैया जय शीतला माता ।\nआदि ज्योति महारानी,\nसब फल की दाता ॥\nॐ जय शीतला माता..॥\nरतन सिंहासन शोभित,\nश्वेत छत्र भाता ।\nऋद्धि-सिद्धि चँवर ढुलावें,\nजगमग छवि छाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nविष्णु सेवत ठाढ़े,\nसेवें शिव धाता ।\nवेद पुराण वरणत,\nपार नहीं पाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nइन्द्र मृदङ्ग बजावत,\nचन्द्र वीणा हाथा ।\nसूरज ताल बजावै,\nनारद मुनि गाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nघण्टा शङ्ख शहनाई,\nबाजै मन भाता ।\nकरै भक्तजन आरती,\nलखि लखि हर्षाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nब्रह्म रूप वरदानी,\nतुही तीन काल ज्ञाता ।\nभक्तन को सुख देती,\nमातु पिता भ्राता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nजो जन ध्यान लगावे,\nप्रेम शक्ति पाता ।\nसकल मनोरथ पावे,\nभवनिधि तर जाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nरोगों से जो पीड़ित कोई,\nशरण तेरी आता ।\nकोढ़ी पावे निर्मल काया,\nअन्ध नेत्र पाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nबांझ पुत्र को पावे,\nदारिद्र कट जाता ।\nताको भजै जो नाहीं,\nसिर धुनि पछताता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nशीतल करती जननी,\nतू ही है जग त्राता ।\nउत्पत्ति व्याधि बिनाशन,\nतू सब की घाता ॥\nॐ जय शीतला माता,\nमैया जय शीतला माता ।\nदास विचित्र कर जोड़े,\nसुन मेरी माता ।\nभक्ति आपनी दीजै,\nऔर न कुछ भाता ॥\nजय शीतला माता,\nमैया जय शीतला माता ।\nआदि ज्योति महारानी,\nसब फल की दाता ॥\nॐ जय शीतला माता..॥",
    "opening": "जय शीतला माता,",
    "romanTitle": "shitla mata aarti",
    "romanLyrics": "jay shitla mata,\nmaiya jay shitla mata .\nadi jyoti maharani,\nsab phal ki data ..\nOm jay shitla mata....\nratan simhasan shobhit,\nshvet chhatra bhata .\nriddhi-siddhi chamvar dhulavem,\njagmag chhavi chhata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nvishnu sevat tharhe,\nsevem shiv dhata .\nved puran varnat,\npar nahim pata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nindra mridangga bajavat,\nchandra vina hatha .\nsuraj tal bajavai,\nnarad muni gata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nghanta shangkha shahanai,\nbajai man bhata .\nkarai bhaktajan aarti,\nlakhi lakhi harshata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nbrahma rup vardani,\ntuhi tin kal jnyata .\nbhaktan ko sukh deti,\nmatu pita bhrata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\njo jan dhyan lagave,\nprem shakti pata .\nsakal manorath pave,\nbhavnidhi tar jata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nrogOm se jo pirit koi,\nsharan teri ata .\nkorhi pave nirmal kaya,\nandh netra pata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nbamjh putra ko pave,\ndaridra kat jata .\ntako bhajai jo nahim,\nsir dhuni pachhtata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\nshital kaarti janni,\ntu hi hai jag trata .\nutpatti vyadhi binashan,\ntu sab ki ghata ..\nOm jay shitla mata,\nmaiya jay shitla mata .\ndas vichitra kar jore,\nsun meri mata .\nbhakti apni dijai,\naur na kuchh bhata ..\njay shitla mata,\nmaiya jay shitla mata .\nadi jyoti maharani,\nsab phal ki data ..\nOm jay shitla mata...."
  },
  {
    "id": 29,
    "category": "नर्मदा",
    "title": "नर्मदा मैया आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-narmada-maiya",
    "lyrics": "ॐ जय जगदानन्दी,\nमैया जय आनंद कन्दी ।\nब्रह्मा हरिहर शंकर, रेवा\nशिव हर‍ि शंकर, रुद्रौ पालन्ती ॥\n॥ ॐ जय जगदानन्दी..॥\nदेवी नारद सारद तुम वरदायक,\nअभिनव पदण्डी ।\nसुर नर मुनि जन सेवत,\nसुर नर मुनि...\nशारद पदवाचन्ती ।\n॥ ॐ जय जगदानन्दी..॥\nदेवी धूमक वाहन राजत,\nवीणा वाद्यन्ती।\nझुमकत-झुमकत-झुमकत,\nझननन झमकत रमती राजन्ती ।\n॥ ॐ जय जगदानन्दी..॥\nदेवी बाजत ताल मृदंगा,\nसुर मण्डल रमती ।\nतोड़ीतान-तोड़ीतान-तोड़ीतान,\nतुरड़ड़ रमती सुरवन्ती ।\n॥ ॐ जय जगदानन्दी..॥\nदेवी सकल भुवन पर आप विराजत,\nनिशदिन आनन्दी ।\nगावत गंगा शंकर, सेवत रेवा\nशंकर तुम भट मेटन्ती ।\n॥ ॐ जय जगदानन्दी...॥\nमैयाजी को कंचन थार विराजत,\nअगर कपूर बाती ।\nअमर कंठ में विराजत,\nघाटन घाट बिराजत,\nकोटि रतन ज्योति ।\n॥ ॐ जय जगदानन्दी..॥\nमैयाजी की आरती,\nनिशदिन पढ़ गा‍वरि,\nहो रेवा जुग-जुग नरगावे,\nभजत शिवानन्द स्वामी\nजपत हर‍ि नंद स्वामी मनवांछित पावे।\nॐ जय जगदानन्दी,\nमैया जय आनंद कन्दी ।\nब्रह्मा हरिहर शंकर, रेवा\nशिव हर‍ि शंकर, रुद्रौ पालन्ती ॥",
    "opening": "ॐ जय जगदानन्दी,",
    "romanTitle": "narmada maiya aarti",
    "romanLyrics": "Om jay jagadanandi,\nmaiya jay anamd kandi .\nbrahma harihar shankar, reva\nshiv hari shankar, rudrau palanti ..\n.. Om jay jagadanandi....\ndevi narad sarad tum varadayak,\nabhinav padandi .\nsur nar muni jan sevat,\nsur nar muni...\nsharad padavachanti .\n.. Om jay jagadanandi....\ndevi dhumak vahan rajat,\nvina vadyanti.\njhumkat-jhumkat-jhumkat,\njhannan jhankat ramti rajanti .\n.. Om jay jagadanandi....\ndevi bajat tal mridamga,\nsur mandal ramti .\ntoritan-toritan-toritan,\nturrar ramti suravanti .\n.. Om jay jagadanandi....\ndevi sakal bhuvan par ap virajat,\nnishdin anandi .\ngavat ganga shankar, sevat reva\nshankar tum bhat metanti .\n.. Om jay jagadanandi.....\nmaiyaji ko kamchan thar virajat,\nagar kapur bati .\namar kamth mem virajat,\nghatan ghat birajat,\nkoti ratan jyoti .\n.. Om jay jagadanandi....\nmaiyaji ki aarti,\nnishdin parh gavari,\nho reva jug-jug nargave,\nbhajat shivanand swami\njapat hari namd swami manavamchhit pave.\nOm jay jagadanandi,\nmaiya jay anamd kandi .\nbrahma harihar shankar, reva\nshiv hari shankar, rudrau palanti .."
  },
  {
    "category": "माँ शैलपुत्री",
    "title": "शैलपुत्री देवी आरती",
    "url": "https://www.bhaktibharat.com/aarti/shailaputri",
    "lyrics": "शैलपुत्री माँ बैल असवार। करें देवता जय जय कार॥\nशिव-शंकर की प्रिय भवानी। तेरी महिमा किसी ने न जानी॥\nपार्वती तू उमा कहलावें। जो तुझे सुमिरे सो सुख पावें॥\nरिद्धि सिद्धि परवान करें तू। दया करें धनवान करें तू॥\nसोमवार को शिव संग प्यारी। आरती जिसने तेरी उतारी॥\nउसकी सगरी आस पुजा दो। सगरे दुःख तकलीफ मिटा दो॥\nघी का सुन्दर दीप जला के। गोला गरी का भोग लगा के॥\nश्रद्धा भाव से मन्त्र जपायें। प्रेम सहित फिर शीश झुकायें॥\nजय गिरराज किशोरी अम्बे। शिव मुख चन्द्र चकोरी अम्बे॥\nमनोकामना पूर्ण कर दो। चमन सदा सुख सम्पत्ति भर दो॥",
    "opening": "शैलपुत्री माँ बैल असवार। करें देवता जय जय कार॥",
    "id": 30,
    "romanTitle": "shailaputri devi aarti",
    "romanLyrics": "shailaputri maa bail asvar. karen devta jay jay kar..\nshiv-shankar ki priy bhavani. teri mahima kisi ne na jani..\nparvati tu uma kahlave. jo tujhe sumire so sukh pavem..\nriddhi siddhi parvan karen tu. daya karen dhanvan karen tu..\nsomvar ko shiv samg pyari. aarti jisne teri utari..\nuski sagri as puja do. sagre duhkh takliph mita do..\nghi ka sundar dip jala ke. gola gari ka bhog laga ke..\nshraddha bhav se mantra japayem. prem sahit phir shish jhukayem..\njay girraj kishori ambe. shiv mukh chandra chakori ambe..\nmanokamna purn kar do. chaman sada sukh sampatti bhar do.."
  },
  {
    "category": "माँ ब्रह्मचारिणी",
    "title": "ब्रह्मचारिणी देवी आरती",
    "url": "https://www.bhaktibharat.com/aarti/aarti-devi-brahmacharini",
    "lyrics": "जय अम्बे ब्रह्मचारिणी माता।\nजय चतुरानन प्रिय सुख दाता॥\nब्रह्मा जी के मन भाती हो।\nज्ञान सभी को सिखलाती हो॥\nब्रह्म मन्त्र है जाप तुम्हारा।\nजिसको जपे सरल संसारा॥\nजय गायत्री वेद की माता।\nजो जन जिस दिन तुम्हें ध्याता॥\nकमी कोई रहने ना पाए।\nकोई भी दुख सहने न पाए॥\nउसकी विरति रहे ठिकाने।\nजो तेरी महिमा को जाने॥\nरद्रक्षा की माला ले कर।\nजपे जो मन्त्र श्रद्धा दे कर॥\nआलस छोड़ करे गुणगाना।\nमाँ तुम उसको सुख पहुँचाना॥\nब्रह्मचारिणी तेरो नाम।\nपूर्ण करो सब मेरे काम॥\nभक्त तेरे चरणों का पुजारी।\nरखना लाज मेरी महतारी॥",
    "opening": "जय अम्बे ब्रह्मचारिणी माता।",
    "id": 31,
    "romanTitle": "brahmacharini devi aarti",
    "romanLyrics": "jay ambe brahmacharini mata.\njay chaturanan priy sukh data..\nbrahma ji ke man bhati ho.\njnyan sabhi ko sikhlati ho..\nbrahma mantra hai jap tumhara.\njisko jape saral samsara..\njay gayatri ved ki mata.\njo jan jis din tumhem dhyata..\nkami koi rahne na pae.\nkoi bhi dukh sahne na pae..\nuski virti rahe thikane.\njo teri mahima ko jane..\nradraksha ki mala le kar.\njape jo mantra shraddha de kar..\nalas chhor kare gungana.\nmaa tum usko sukh pahumchana..\nbrahmacharini tero nam.\npurn karo sab mere kam..\nbhakt tere charnOm ka pujari.\nrakhna laj meri mahtari.."
  },
  {
    "category": "माँ महागौरी",
    "title": "महागौरी देवी आरती",
    "url": "https://www.bhaktibharat.com/aarti/mahagauri-aarti",
    "lyrics": "जय महागौरी जगत की माया।\nजय उमा भवानी जय महामाया॥\nहरिद्वार कनखल के पासा।\nमहागौरी तेरा वहा निवास॥\nचन्द्रकली और ममता अम्बे।\nजय शक्ति जय जय माँ जगदम्बे॥\nभीमा देवी विमला माता।\nकौशिक देवी जग विख्यता॥\nहिमाचल के घर गौरी रूप तेरा।\nमहाकाली दुर्गा है स्वरूप तेरा॥\nसती (सत) हवन कुंड में था जलाया।\nउसी धुएं ने रूप काली बनाया॥\nबना धर्म सिंह जो सवारी में आया।\nतो शंकर ने त्रिशूल अपना दिखाया॥\nतभी माँ ने महागौरी नाम पाया।\nशरण आनेवाले का संकट मिटाया॥\nशनिवार को तेरी पूजा जो करता।\nमाँ बिगड़ा हुआ काम उसका सुधरता॥\nभक्त बोलो तो सोच तुम क्या रहे हो।\nमहागौरी माँ तेरी हरदम ही जय हो॥",
    "opening": "जय महागौरी जगत की माया।",
    "id": 32,
    "romanTitle": "mahagauri devi aarti",
    "romanLyrics": "jay mahagauri jagat ki maya.\njay uma bhavani jay mahamaya..\nharidvar kankhal ke pasa.\nmahagauri tera vaha nivas..\nchandrakli aur mata ambe.\njay shakti jay jay maa jagadambe..\nbhima devi vimla mata.\nkaushik devi jag vikhyata..\nhimachal ke ghar gauri rup tera.\nmahakali durga hai svarup tera..\nsati (sat) havan kumd mem tha jalaya.\nusi dhuem ne rup kali banaya..\nbana dharm simh jo savari mem aya.\nto shankar ne trishul apna dikhaya..\ntabhi maa ne mahagauri nam paya.\nsharan anevale ka sankat mitaya..\nshanivar ko teri puja jo karta.\nmaa bigra hua kam uska sudhrata..\nbhakt bolo to soch tum kya rahe ho.\nmahagauri maa teri hardam hi jay ho.."
  },
  {
    "category": "माँ कात्यायनी",
    "title": "कात्यायनी देवी आरती",
    "url": "https://www.bhaktibharat.com/aarti/katyayani-aarti",
    "lyrics": "जय जय अम्बे जय कात्यायनी।\nजय जग माता जग की महारानी॥\nबैजनाथ स्थान तुम्हारा।\nवहावर दाती नाम पुकारा॥\nकई नाम है कई धाम है।\nयह स्थान भी तो सुखधाम है॥\nहर मन्दिर में ज्योत तुम्हारी।\nकही योगेश्वरी महिमा न्यारी॥\nहर जगह उत्सव होते रहते।\nहर मन्दिर में भगत है कहते॥\nकत्यानी रक्षक काया की।\nग्रंथि काटे मोह माया की॥\nझूठे मोह से छुडाने वाली।\nअपना नाम जपाने वाली॥\nबृहस्पतिवार को पूजा करिए।\nध्यान कात्यानी का धरिये॥\nहर संकट को दूर करेगी।\nभंडारे भरपूर करेगी॥\nजो भी माँ को भक्त पुकारे।\nकात्यायनी सब कष्ट निवारे॥",
    "opening": "जय जय अम्बे जय कात्यायनी।",
    "id": 33,
    "romanTitle": "katyayni devi aarti",
    "romanLyrics": "jay jay ambe jay katyayni.\njay jag mata jag ki maharani..\nbaijnath sthan tumhara.\nvahavar dati nam pukara..\nkai nam hai kai dham hai.\nyah sthan bhi to sukhdham hai..\nhar mandir mem jyot tumhari.\nkahi yogeshvari mahima nyari..\nhar jagah utsav hote rahte.\nhar mandir mem bhagat hai kahte..\nkatyani rakshak kaya ki.\ngramthi kate moh maya ki..\njhuthe moh se chhudane vali.\napna nam japane vali..\nbrihaspativar ko puja karie.\ndhyan katyani ka dhariye..\nhar sankat ko dur karegi.\nbhamdare bharpur karegi..\njo bhi maa ko bhakt pukare.\nkatyayni sab kasht nivare.."
  },
  {
    "category": "माँ स्कंदमाता",
    "title": "स्कंदमाता आरती",
    "url": "https://www.bhaktibharat.com/aarti/skandamata-aarti",
    "lyrics": "जय तेरी हो स्कन्द माता।\nपांचवां नाम तुम्हारा आता॥\nसबके मन की जानन हारी।\nजग जननी सबकी महतारी॥\nतेरी जोत जलाता रहूं मैं।\nहरदम तुझे ध्याता रहूं मै॥\nकई नामों से तुझे पुकारा।\nमुझे एक है तेरा सहारा॥\nकही पहाड़ों पर है डेरा।\nकई शहरों में तेरा बसेरा॥\nहर मन्दिर में तेरे नजारे।\nगुण गाए तेरे भक्त प्यारे॥\nभक्ति अपनी मुझे दिला दो।\nशक्ति मेरी बिगड़ी बना दो॥\nइन्द्र आदि देवता मिल सारे।\nकरे पुकार तुम्हारे द्वारे॥\nदुष्ट दैत्य जब चढ़ कर आए।\nतू ही खण्ड हाथ उठाए॥\nदासों को सदा बचाने आयी।\nभक्त की आस पुजाने आयी॥",
    "opening": "जय तेरी हो स्कन्द माता।",
    "id": 34,
    "romanTitle": "skamdmata aarti",
    "romanLyrics": "jay teri ho skand mata.\npamchvam nam tumhara ata..\nsabke man ki janan hari.\njag janni sabki mahtari..\nteri jot jalata rahum maim.\nhardam tujhe dhyata rahum mai..\nkai namOm se tujhe pukara.\nmujhe ek hai tera sahara..\nkahi paharOm par hai dera.\nkai shahrOm mem tera basera..\nhar mandir mem tere najare.\ngun gae tere bhakt pyare..\nbhakti apni mujhe dila do.\nshakti meri bigri bana do..\nindra adi devta mil sare.\nkare pukar tumhare dvare..\ndusht daitya jab charh kar ae.\ntu hi khand hath uthae..\ndasom ko sada bachane ayi.\nbhakt ki as pujane ayi.."
  },
  {
    "category": "माँ चन्द्रघण्टा",
    "title": "चन्द्रघण्टा देवी आरती",
    "url": "https://www.bhaktibharat.com/aarti/mata-chandraghanta-aarti",
    "lyrics": "जय माँ चन्द्रघण्टा सुख धाम।\nपूर्ण कीजो मेरे काम॥\nचन्द्र समाज तू शीतल दाती।\nचन्द्र तेज किरणों में समाती॥\nमन की मालक मन भाती हो।\nचन्द्रघण्टा तुम वर दाती हो॥\nसुन्दर भाव को लाने वाली।\nहर संकट में बचाने वाली॥\nहर बुधवार को तुझे ध्याये।\nश्रद्धा सहित तो विनय सुनाए॥\nमूर्ति चन्द्र आकार बनाए।\nसन्मुख घी की ज्योत जलाएं॥\nशीश झुका कहे मन की बाता।\nपूर्ण आस करो जगत दाता॥\nकांचीपुर स्थान तुम्हारा।\nकर्नाटिका में मान तुम्हारा॥\nनाम तेरा रटू महारानी।\nभक्त की रक्षा करो भवानी॥",
    "opening": "जय माँ चन्द्रघण्टा सुख धाम।",
    "id": 35,
    "romanTitle": "chandraghanta devi aarti",
    "romanLyrics": "jay maa chandraghanta sukh dham.\npurn kijo mere kam..\nchandra samaj tu shital dati.\nchandra tej kirnOm mem samati..\nman ki malak man bhati ho.\nchandraghanta tum var dati ho..\nsundar bhav ko lane vali.\nhar sankat mem bachane vali..\nhar budhvar ko tujhe dhyaye.\nshraddha sahit to vinay sunae..\nmurti chandra akar banae.\nsanmukh ghi ki jyot jalaem..\nshish jhuka kahe man ki bata.\npurn as karo jagat data..\nkamchipur sthan tumhara.\nkarnatika mem man tumhara..\nnam tera ratu maharani.\nbhakt ki raksha karo bhavani.."
  },
  {
    "category": "अहोई माता",
    "title": "अहोई माता आरती",
    "url": "https://www.bhaktibharat.com/aarti/ahoi-mata-aarti",
    "lyrics": "जय अहोई माता,\nजय अहोई माता ।\nतुमको निसदिन ध्यावत,\nहर विष्णु विधाता ॥\nॐ जय अहोई माता ॥\nब्रह्माणी, रुद्राणी, कमला,\nतू ही है जगमाता ।\nसूर्य-चन्द्रमा ध्यावत,\nनारद ऋषि गाता ॥\nॐ जय अहोई माता ॥\nमाता रूप निरंजन,\nसुख-सम्पत्ति दाता ।\nजो कोई तुमको ध्यावत,\nनित मंगल पाता ॥\nॐ जय अहोई माता ॥\nतू ही पाताल बसंती,\nतू ही है शुभदाता ।\nकर्म-प्रभाव प्रकाशक,\nजगनिधि से त्राता ॥\nॐ जय अहोई माता ॥\nजिस घर थारो वासा,\nवाहि में गुण आता ।\nकर न सके सोई कर ले,\nमन नहीं घबराता ॥\nॐ जय अहोई माता ॥\nतुम बिन सुख न होवे,\nन कोई पुत्र पाता ।\nखान-पान का वैभव,\nतुम बिन नहीं आता ॥\nॐ जय अहोई माता ॥\nशुभ गुण सुंदर युक्ता,\nक्षीर निधि जाता ।\nरतन चतुर्दश तोकू,\nकोई नहीं पाता ॥\nॐ जय अहोई माता ॥\nश्री अहोई माँ की आरती,\nजो कोई गाता ।\nउर उमंग अति उपजे,\nपाप उतर जाता ॥\nॐ जय अहोई माता,\nमैया जय अहोई माता ।",
    "opening": "जय अहोई माता,",
    "id": 36,
    "romanTitle": "ahoi mata aarti",
    "romanLyrics": "jay ahoi mata,\njay ahoi mata .\ntumko nisdin dhyavat,\nhar vishnu vidhata ..\nOm jay ahoi mata ..\nbrahmani, rudrani, kamla,\ntu hi hai jagmata .\nsurya-chandrama dhyavat,\nnarad rishi gata ..\nOm jay ahoi mata ..\nmata rup niramjan,\nsukh-sampatti data .\njo koi tumko dhyavat,\nnit maagal pata ..\nOm jay ahoi mata ..\ntu hi patal basamti,\ntu hi hai shubhdata .\nkarm-prabhav prakashak,\njagnidhi se trata ..\nOm jay ahoi mata ..\njis ghar tharo vasa,\nvahi mem gun ata .\nkar na sake soi kar le,\nman nahim ghabrata ..\nOm jay ahoi mata ..\ntum bin sukh na hove,\nna koi putra pata .\nkhan-pan ka vaibhav,\ntum bin nahim ata ..\nOm jay ahoi mata ..\nshubh gun sumdar yukta,\nkshir nidhi jata .\nratan chaturdash toku,\nkoi nahim pata ..\nOm jay ahoi mata ..\nshri ahoi maa ki aarti,\njo koi gata .\nur umaag ati upje,\npap utar jata ..\nOm jay ahoi mata,\nmaiya jay ahoi mata ."
  },
  {
    "category": "चन्द्र देव",
    "title": "चन्द्र देव आरती",
    "url": "https://www.bhaktibharat.com/aarti/chandra-dev-aarti",
    "lyrics": "ॐ जय सोम देवा, स्वामी जय सोम देवा ।\nदुःख हरता सुख करता, जय आनन्दकारी ।\nरजत सिंहासन राजत, ज्योति तेरी न्यारी ।\nदीन दयाल दयानिधि, भव बन्धन हारी ।\nजो कोई आरती तेरी, प्रेम सहित गावे ।\nसकल मनोरथ दायक, निर्गुण सुखराशि ।\nयोगीजन हृदय में, तेरा ध्यान धरें ।\nब्रह्मा विष्णु सदाशिव, सन्त करें सेवा ।\nवेद पुराण बखानत, भय पातक हारी ।\nप्रेमभाव से पूजें, सब जग के नारी ।\nशरणागत प्रतिपालक, भक्तन हितकारी ।\nधन सम्पत्ति और वैभव, सहजे सो पावे ।\nविश्व चराचर पालक, ईश्वर अविनाशी ।\nसब जग के नर नारी, पूजा पाठ करें ।\nॐ जय सोम देवा, स्वामी जय सोम देवा ।",
    "opening": "ॐ जय सोम देवा, स्वामी जय सोम देवा ।",
    "id": 37,
    "romanTitle": "chandra dev aarti",
    "romanLyrics": "Om jay som deva, swami jay som deva .\nduhkh harta sukh karta, jay anandakari .\nrajat simhasan rajat, jyoti teri nyari .\ndin dayal dayanidhi, bhav bandhan hari .\njo koi aarti teri, prem sahit gave .\nsakal manorath dayak, nirgun sukhrashi .\nyogijan hriday mem, tera dhyan dharem .\nbrahma vishnu sadashiv, sant karen seva .\nved puran bakhanat, bhay patak hari .\nprembhav se pujem, sab jag ke nari .\nsharanagat pratipalak, bhaktan hitkari .\ndhan sampatti aur vaibhav, sahje so pave .\nvishva charachar palak, ishvar avinashi .\nsab jag ke nar nari, puja path karen .\nOm jay som deva, swami jay som deva ."
  },
  {
    "category": "भैरव",
    "title": "भैरव जी की आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-bhairav-ji",
    "lyrics": "जय भैरव देवा, प्रभु जय भैरव देवा ।\nजय काली और गौर देवी कृत सेवा ॥\n॥ जय भैरव देवा...॥\nतुम्ही पाप उद्धारक दुःख सिन्धु तारक ।\nभक्तो के सुख कारक भीषण वपु धारक ॥\n॥ जय भैरव देवा...॥\nवाहन श्वान विराजत कर त्रिशूल धारी ।\nमहिमा अमित तुम्हारी जय जय भयहारी ॥\n॥ जय भैरव देवा...॥\nतुम बिन देवा सेवा सफल नहीं होवे ।\nचौमुख दीपक दर्शन दुःख खोवे ॥\n॥ जय भैरव देवा...॥\nतेल चटकी दधि मिश्रित भाषावाली तेरी ।\nकृपा कीजिये भैरव, करिए नहीं देरी ॥\n॥ जय भैरव देवा...॥\nपाँव घुँघरू बाजत अरु डमरू दम्कावत ।\nबटुकनाथ बन बालक जल मन हरषावत ॥\n॥ जय भैरव देवा...॥\nबटुकनाथ जी की आरती जो कोई नर गावे ।\nकहे धरनी धर नर मनवांछित फल पावे ॥\n॥ जय भैरव देवा...॥",
    "opening": "जय भैरव देवा, प्रभु जय भैरव देवा ।",
    "id": 38,
    "romanTitle": "bhairav ji ki aarti",
    "romanLyrics": "jay bhairav deva, prabhu jay bhairav deva .\njay kali aur gaur devi krit seva ..\n.. jay bhairav deva.....\ntumhi pap uddharak duhkh sindhu tarak .\nbhakto ke sukh karak bhishan vapu dharak ..\n.. jay bhairav deva.....\nvahan shvan virajat kar trishul dhari .\nmahima amit tumhari jay jay bhayhari ..\n.. jay bhairav deva.....\ntum bin deva seva saphal nahim hove .\nchaumukh dipak darshan duhkh khove ..\n.. jay bhairav deva.....\ntel chatki dadhi mishrit bhashavali teri .\nkripa kijiye bhairav, karie nahim deri ..\n.. jay bhairav deva.....\npamv ghumghru bajat aru damru dankavat .\nbatuknath ban balak jal man harashavat ..\n.. jay bhairav deva.....\nbatuknath ji ki aarti jo koi nar gave .\nkahe dharni dhar nar manavamchhit phal pave ..\n.. jay bhairav deva....."
  },
  {
    "category": "सीता",
    "title": "श्री सीता माता आरती",
    "url": "https://www.bhaktibharat.com/aarti/shri-sita-mata",
    "lyrics": "आरती श्री जनक दुलारी की ।\nसीता जी रघुवर प्यारी की ॥\nजगत जननी जग की विस्तारिणी,\nनित्य सत्य साकेत विहारिणी,\nपरम दयामयी दिनोधारिणी,\nसीता मैया भक्तन हितकारी की ॥\nआरती श्री जनक दुलारी की ।\nसीता जी रघुवर प्यारी की ॥\nसती श्रोमणि पति हित कारिणी,\nपति सेवा वित्त वन वन चारिणी,\nपति हित पति वियोग स्वीकारिणी,\nत्याग धर्म मूर्ति धरी की ॥\nआरती श्री जनक दुलारी की ।\nसीता जी रघुवर प्यारी की ॥\nविमल कीर्ति सब लोकन छाई,\nनाम लेत पवन मति आई,\nसुमीरात काटत कष्ट दुख दाई,\nशरणागत जन भय हरी की ॥\nआरती श्री जनक दुलारी की ।\nसीता जी रघुवर प्यारी की ॥",
    "opening": "आरती श्री जनक दुलारी की ।",
    "id": 39,
    "romanTitle": "shri sita mata aarti",
    "romanLyrics": "aarti shri janak dulari ki .\nsita ji raghuvar pyari ki ..\njagat janni jag ki vistarini,\nnitya satya saket viharini,\nparam dayamyi dinodharini,\nsita maiya bhaktan hitkari ki ..\naarti shri janak dulari ki .\nsita ji raghuvar pyari ki ..\nsati shromni pati hit karini,\npati seva vitt van van charini,\npati hit pati viyog svikarini,\ntyag dharm murti dhari ki ..\naarti shri janak dulari ki .\nsita ji raghuvar pyari ki ..\nvimal kirti sab lokan chhai,\nnam let pavan mati ai,\nsumirat katat kasht dukh dai,\nsharanagat jan bhay hari ki ..\naarti shri janak dulari ki .\nsita ji raghuvar pyari ki .."
  },
  {
    "category": "महावीर",
    "title": "ॐ जय महावीर प्रभु",
    "url": "https://www.bhaktibharat.com/aarti/om-jai-mahavir-prabhu",
    "lyrics": "ॐ जय महावीर प्रभु,\nस्वामी जय महावीर प्रभु ।\nकुण्डलपुर अवतारी,\nचांदनपुर अवतारी,\nत्रिशलानंद विभु ॥\nसिध्धारथ घर जन्मे,\nवैभव था भारी ।\nबाल ब्रह्मचारी व्रत,\nपाल्यो तप धारी ॥\nॐ जय महावीर प्रभु...॥\nआतम ज्ञान विरागी,\nसम दृष्टि धारी ।\nमाया मोह विनाशक,\nज्ञान ज्योति जारी ॥\nॐ जय महावीर प्रभु...॥\nजग में पाठ अहिंसा,\nआप ही विस्तारयो ।\nहिंसा पाप मिटा कर,\nसुधर्म परिचारियो ॥\nॐ जय महावीर प्रभु...॥\nअमर चंद को सपना,\nतुमने परभू दीना ।\nमंदिर तीन शेखर का,\nनिर्मित है कीना ॥\nॐ जय महावीर प्रभु...॥\nजयपुर नृप भी तेरे,\nअतिशय के सेवी ।\nएक ग्राम तिन्ह दीनो,\nसेवा हित यह भी ॥\nॐ जय महावीर प्रभु...॥\nजल में भिन्न कमल जो,\nघर में बाल यति ।\nराज पाठ सब त्यागे,\nममता मोह हती ॥\nॐ जय महावीर प्रभु...॥\nभूमंडल चांदनपुर,\nमंदिर मध्य लसे ।\nशांत जिनिश्वर मूरत,\nदर्शन पाप लसे ॥\nॐ जय महावीर प्रभु...॥\nजो कोई तेरे दर पर,\nइच्छा कर आवे ।\nधन सुत्त सब कुछ पावे,\nसंकट मिट जावे ॥\nॐ जय महावीर प्रभु...॥\nनिशदिन प्रभु मंदिर में,\nजगमग ज्योत जरे ।\nहम सेवक चरणों में,\nआनंद मूँद भरे ॥\nॐ जय महावीर प्रभु...॥\nॐ जय महावीर प्रभु,\nस्वामी जय महावीर प्रभु ।\nकुण्डलपुर अवतारी,\nचांदनपुर अवतारी,\nत्रिशलानंद विभु ॥",
    "opening": "ॐ जय महावीर प्रभु,",
    "id": 40,
    "romanTitle": "Om jay mahavir prabhu",
    "romanLyrics": "Om jay mahavir prabhu,\nswami jay mahavir prabhu .\nkundalpur avtari,\nchamdanpur avtari,\ntrishalanamd vibhu ..\nsidhdharath ghar janme,\nvaibhav tha bhari .\nbal brahmachari vrat,\npalyo tap dhari ..\nOm jay mahavir prabhu.....\natam jnyan viragi,\nsam drishti dhari .\nmaya moh vinashak,\njnyan jyoti jari ..\nOm jay mahavir prabhu.....\njag mem path ahimsa,\nap hi vistaryo .\nhimsa pap mita kar,\nsudharm parichariyo ..\nOm jay mahavir prabhu.....\namar chamd ko sapna,\ntumne parbhu dina .\nmandir tin shekhar ka,\nnirmit hai kina ..\nOm jay mahavir prabhu.....\njaypur nrip bhi tere,\natishay ke sevi .\nek gram tinha dino,\nseva hit yah bhi ..\nOm jay mahavir prabhu.....\njal mem bhinn kamal jo,\nghar mem bal yati .\nraj path sab tyage,\nmata moh hati ..\nOm jay mahavir prabhu.....\nbhumandal chamdanpur,\nmandir madhya lase .\nshamt jinishvar murat,\ndarshan pap lase ..\nOm jay mahavir prabhu.....\njo koi tere dar par,\nichchha kar ave .\ndhan sutt sab kuchh pave,\nsankat mit jave ..\nOm jay mahavir prabhu.....\nnishdin prabhu mandir mem,\njagmag jyot jare .\nham sevak charnOm mem,\nanamd mumd bhare ..\nOm jay mahavir prabhu.....\nOm jay mahavir prabhu,\nswami jay mahavir prabhu .\nkundalpur avtari,\nchamdanpur avtari,\ntrishalanamd vibhu .."
  }
];
